/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`payments_checkout`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PaymentsCheckoutError {
    Status400(models::ApiErrorResponseDto),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`payments_controller_handle_stk_callback`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PaymentsControllerHandleStkCallbackError {
    UnknownValue(serde_json::Value),
}


pub async fn payments_checkout(configuration: &configuration::Configuration, org_slug: &str, checkout_dto: models::CheckoutDto) -> Result<models::CheckoutResponseDto, Error<PaymentsCheckoutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_body_checkout_dto = checkout_dto;

    let uri_str = format!("{}/v3/{orgSlug}/payments/checkout", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_checkout_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CheckoutResponseDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CheckoutResponseDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PaymentsCheckoutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn payments_controller_handle_stk_callback(configuration: &configuration::Configuration, org_slug: &str, payment_id: &str) -> Result<(), Error<PaymentsControllerHandleStkCallbackError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_path_payment_id = payment_id;

    let uri_str = format!("{}/v3/{orgSlug}/payments/webhooks/mpesa/stkpush/{paymentId}", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug), paymentId=crate::apis::urlencode(p_path_payment_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<PaymentsControllerHandleStkCallbackError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

