/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`auth_controller_handle_o_auth2`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthControllerHandleOAuth2Error {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`auth_exchange_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthExchangeTokenError {
    Status401(models::ApiErrorResponseDto),
    UnknownValue(serde_json::Value),
}


/// Proxies OAuth2 requests (authorize, token, userinfo, etc.) to the auth provider
pub async fn auth_controller_handle_o_auth2(configuration: &configuration::Configuration, path: &str) -> Result<(), Error<AuthControllerHandleOAuth2Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_path = path;

    let uri_str = format!("{}/v3/auth/oauth2/{path}", configuration.base_path, path=crate::apis::urlencode(p_path_path));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthControllerHandleOAuth2Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn auth_exchange_token(configuration: &configuration::Configuration, token_request_dto: models::TokenRequestDto) -> Result<models::AuthExchangeToken201Response, Error<AuthExchangeTokenError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_token_request_dto = token_request_dto;

    let uri_str = format!("{}/v3/auth/token", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_token_request_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthExchangeToken201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthExchangeToken201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthExchangeTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

