/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`p_os_get_me`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsGetMeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_get_petty_cash_funds`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsGetPettyCashFundsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_get_petty_cash_transactions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsGetPettyCashTransactionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_get_transactions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsGetTransactionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsLoginError {
    Status401(models::ApiErrorResponseDto),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_process_sale`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsProcessSaleError {
    Status400(models::ApiErrorResponseDto),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_provision`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsProvisionError {
    Status400(models::ApiErrorResponseDto),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_register_petty_cash`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsRegisterPettyCashError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`p_os_sync`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum POsSyncError {
    UnknownValue(serde_json::Value),
}


pub async fn p_os_get_me(configuration: &configuration::Configuration, org_slug: &str) -> Result<(), Error<POsGetMeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/pos/me", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<POsGetMeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_get_petty_cash_funds(configuration: &configuration::Configuration, org_slug: &str) -> Result<(), Error<POsGetPettyCashFundsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/pos/petty-cash/funds", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<POsGetPettyCashFundsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_get_petty_cash_transactions(configuration: &configuration::Configuration, limit: &str, org_slug: &str) -> Result<(), Error<POsGetPettyCashTransactionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_limit = limit;
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/pos/petty-cash/transactions", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("limit", &p_query_limit.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<POsGetPettyCashTransactionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_get_transactions(configuration: &configuration::Configuration, org_slug: &str) -> Result<(), Error<POsGetTransactionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/pos/transactions", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<POsGetTransactionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_login(configuration: &configuration::Configuration, org_slug: &str, pos_login_dto: models::PosLoginDto) -> Result<models::PosLoginResponseDto, Error<POsLoginError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_body_pos_login_dto = pos_login_dto;

    let uri_str = format!("{}/v3/{orgSlug}/pos/login", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_pos_login_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PosLoginResponseDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PosLoginResponseDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<POsLoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_process_sale(configuration: &configuration::Configuration, org_slug: &str, process_sale_dto: models::ProcessSaleDto) -> Result<(), Error<POsProcessSaleError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_body_process_sale_dto = process_sale_dto;

    let uri_str = format!("{}/v3/{orgSlug}/pos/sale", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_process_sale_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<POsProcessSaleError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_provision(configuration: &configuration::Configuration, org_slug: &str, provision_device_dto: models::ProvisionDeviceDto) -> Result<models::ProvisionResponseDto, Error<POsProvisionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_body_provision_device_dto = provision_device_dto;

    let uri_str = format!("{}/v3/{orgSlug}/pos/provision", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_provision_device_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProvisionResponseDto`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProvisionResponseDto`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<POsProvisionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_register_petty_cash(configuration: &configuration::Configuration, org_slug: &str, register_petty_cash_dto: models::RegisterPettyCashDto) -> Result<(), Error<POsRegisterPettyCashError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_body_register_petty_cash_dto = register_petty_cash_dto;

    let uri_str = format!("{}/v3/{orgSlug}/pos/petty-cash", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_register_petty_cash_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<POsRegisterPettyCashError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn p_os_sync(configuration: &configuration::Configuration, org_slug: &str) -> Result<(), Error<POsSyncError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/pos/sync", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<POsSyncError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

