/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcceptInvitationDto {
    #[serde(rename = "token")]
    pub token: String,
}

impl AcceptInvitationDto {
    pub fn new(token: String) -> AcceptInvitationDto {
        AcceptInvitationDto {
            token,
        }
    }
}
