/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateDeviceDto {
    /// The secure setup token
    #[serde(rename = "token")]
    pub token: String,
    /// Unique hardware machine ID
    #[serde(rename = "machineId")]
    pub machine_id: String,
    /// Device hardware fingerprint
    #[serde(rename = "fingerprint", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,
    /// Device serial number
    #[serde(rename = "serialNumber", skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
}

impl ActivateDeviceDto {
    pub fn new(token: String, machine_id: String) -> ActivateDeviceDto {
        ActivateDeviceDto {
            token,
            machine_id,
            fingerprint: None,
            serial_number: None,
        }
    }
}
