/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddDepartmentMemberDto {
    #[serde(rename = "memberId")]
    pub member_id: String,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    #[serde(rename = "canApproveExpenses", skip_serializing_if = "Option::is_none")]
    pub can_approve_expenses: Option<bool>,
    #[serde(rename = "canManageBudget", skip_serializing_if = "Option::is_none")]
    pub can_manage_budget: Option<bool>,
}

impl AddDepartmentMemberDto {
    pub fn new(member_id: String) -> AddDepartmentMemberDto {
        AddDepartmentMemberDto {
            member_id,
            role: None,
            can_approve_expenses: None,
            can_manage_budget: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "HEAD")]
    Head,
    #[serde(rename = "MANAGER")]
    Manager,
    #[serde(rename = "MEMBER")]
    Member,
    #[serde(rename = "VIEWER")]
    Viewer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Head
    }
}
