/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddToCartDto {
    #[serde(rename = "productId", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<String>,
    #[serde(rename = "variantId", skip_serializing_if = "Option::is_none")]
    pub variant_id: Option<String>,
    #[serde(rename = "serviceId", skip_serializing_if = "Option::is_none")]
    pub service_id: Option<String>,
    #[serde(rename = "bookingDetails", skip_serializing_if = "Option::is_none")]
    pub booking_details: Option<serde_json::Value>,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "sessionId", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
}

impl AddToCartDto {
    pub fn new(quantity: f64) -> AddToCartDto {
        AddToCartDto {
            product_id: None,
            variant_id: None,
            service_id: None,
            booking_details: None,
            quantity,
            session_id: None,
            customer_id: None,
        }
    }
}

