/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnouncementDto {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "targetBranchId", skip_serializing_if = "Option::is_none")]
    pub target_branch_id: Option<String>,
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
}

impl AnnouncementDto {
    pub fn new(title: String, message: String) -> AnnouncementDto {
        AnnouncementDto {
            title,
            message,
            target_branch_id: None,
            severity: None,
        }
    }
}
