/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorResponseDto {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "error")]
    pub error: serde_json::Value,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl ApiErrorResponseDto {
    pub fn new(success: bool, error: serde_json::Value, timestamp: String) -> ApiErrorResponseDto {
        ApiErrorResponseDto {
            success,
            error,
            timestamp,
        }
    }
}
