/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2BQuoteItemDto {
    #[serde(rename = "variantId")]
    pub variant_id: String,
    #[serde(rename = "quantity")]
    pub quantity: f64,
}

impl B2BQuoteItemDto {
    pub fn new(variant_id: String, quantity: f64) -> B2BQuoteItemDto {
        B2BQuoteItemDto {
            variant_id,
            quantity,
        }
    }
}
