/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2BOrderItemDto {
    /// The ID of the product variant
    #[serde(rename = "variantId")]
    pub variant_id: String,
    /// Quantity to order
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// Price per unit
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
}

impl B2BOrderItemDto {
    pub fn new(variant_id: String, quantity: f64) -> B2BOrderItemDto {
        B2BOrderItemDto {
            variant_id,
            quantity,
            price: None,
        }
    }
}
