/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct B2BVariantStockDto {
    #[serde(rename = "availableStock")]
    pub available_stock: f64,
    #[serde(rename = "locationId")]
    pub location_id: String,
}

impl B2BVariantStockDto {
    pub fn new(available_stock: f64, location_id: String) -> B2BVariantStockDto {
        B2BVariantStockDto {
            available_stock,
            location_id,
        }
    }
}
