/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteBookingDto {
    /// Actual materials consumed
    #[serde(rename = "materials", skip_serializing_if = "Option::is_none")]
    pub materials: Option<Vec<models::ServiceMaterialDto>>,
    /// Actual start time
    #[serde(rename = "actualStartTime", skip_serializing_if = "Option::is_none")]
    pub actual_start_time: Option<String>,
    /// Actual end time
    #[serde(rename = "actualEndTime", skip_serializing_if = "Option::is_none")]
    pub actual_end_time: Option<String>,
}

impl CompleteBookingDto {
    pub fn new() -> CompleteBookingDto {
        CompleteBookingDto {
            materials: None,
            actual_start_time: None,
            actual_end_time: None,
        }
    }
}
