/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCrmObjectDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "labelPlural")]
    pub label_plural: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "icon")]
    pub icon: String,
}

impl CreateCrmObjectDto {
    pub fn new(name: String, label: String, label_plural: String, description: String, icon: String) -> CreateCrmObjectDto {
        CreateCrmObjectDto {
            name,
            label,
            label_plural,
            description,
            icon,
        }
    }
}

