/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInvitationDto {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "departmentIds", skip_serializing_if = "Option::is_none")]
    pub department_ids: Option<Vec<String>>,
    #[serde(rename = "customRoleIds", skip_serializing_if = "Option::is_none")]
    pub custom_role_ids: Option<Vec<String>>,
    #[serde(rename = "roleGroupIds", skip_serializing_if = "Option::is_none")]
    pub role_group_ids: Option<Vec<String>>,
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "isGuestInvite", skip_serializing_if = "Option::is_none")]
    pub is_guest_invite: Option<bool>,
}

impl CreateInvitationDto {
    pub fn new(email: String, role: Role) -> CreateInvitationDto {
        CreateInvitationDto {
            email,
            role,
            department_ids: None,
            custom_role_ids: None,
            role_group_ids: None,
            expires_at: None,
            is_guest_invite: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "OWNER")]
    Owner,
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "MANAGER")]
    Manager,
    #[serde(rename = "EMPLOYEE")]
    Employee,
    #[serde(rename = "CASHIER")]
    Cashier,
    #[serde(rename = "REPORTER")]
    Reporter,
    #[serde(rename = "GUEST")]
    Guest,
}

impl Default for Role {
    fn default() -> Role {
        Self::Owner
    }
}
