/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePurchaseItemDto {
    #[serde(rename = "variantId")]
    pub variant_id: String,
    #[serde(rename = "orderedQuantity")]
    pub ordered_quantity: f64,
    #[serde(rename = "unitCost")]
    pub unit_cost: f64,
    #[serde(rename = "orderedUnitId", skip_serializing_if = "Option::is_none")]
    pub ordered_unit_id: Option<String>,
    #[serde(rename = "orderedOrgUnitId", skip_serializing_if = "Option::is_none")]
    pub ordered_org_unit_id: Option<String>,
}

impl CreatePurchaseItemDto {
    pub fn new(variant_id: String, ordered_quantity: f64, unit_cost: f64) -> CreatePurchaseItemDto {
        CreatePurchaseItemDto {
            variant_id,
            ordered_quantity,
            unit_cost,
            ordered_unit_id: None,
            ordered_org_unit_id: None,
        }
    }
}
