/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCrmFieldDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl CreateCrmFieldDto {
    pub fn new(name: String, label: String, r#type: Type) -> CreateCrmFieldDto {
        CreateCrmFieldDto {
            name,
            label,
            r#type,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "TEXT")]
    Text,
    #[serde(rename = "NUMBER")]
    Number,
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "DATE")]
    Date,
    #[serde(rename = "SELECT")]
    Select,
    #[serde(rename = "MULTI_SELECT")]
    MultiSelect,
    #[serde(rename = "EMAIL")]
    Email,
    #[serde(rename = "PHONE")]
    Phone,
    #[serde(rename = "URL")]
    Url,
    #[serde(rename = "JSON")]
    Json,
}

impl Default for Type {
    fn default() -> Type {
        Self::Text
    }
}
