/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrderDto {
    /// Internal customer ID.
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    /// Internal business account ID.
    #[serde(rename = "businessAccountId", skip_serializing_if = "Option::is_none")]
    pub business_account_id: Option<String>,
    /// Inventory location ID
    #[serde(rename = "locationId")]
    pub location_id: String,
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::OrderItemDto>>,
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Vec<models::ServiceBookingItemDto>>,
    #[serde(rename = "shippingAddress", skip_serializing_if = "Option::is_none")]
    pub shipping_address: Option<Box<models::AddressDto>>,
    #[serde(rename = "channel")]
    pub channel: Channel,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl CreateOrderDto {
    pub fn new(location_id: String, channel: Channel) -> CreateOrderDto {
        CreateOrderDto {
            customer_id: None,
            business_account_id: None,
            location_id,
            items: None,
            services: None,
            shipping_address: None,
            channel,
            notes: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Channel {
    #[serde(rename = "ECOMMERCE_STORE")]
    EcommerceStore,
    #[serde(rename = "MOBILE_APP")]
    MobileApp,
}

impl Default for Channel {
    fn default() -> Channel {
        Self::EcommerceStore
    }
}
