/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePettyCashFundDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "floatAmount")]
    pub float_amount: f64,
    #[serde(rename = "currencyCode", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<String>,
    #[serde(rename = "responsibleMemberId")]
    pub responsible_member_id: String,
}

impl CreatePettyCashFundDto {
    pub fn new(name: String, float_amount: f64, responsible_member_id: String) -> CreatePettyCashFundDto {
        CreatePettyCashFundDto {
            name,
            float_amount,
            currency_code: None,
            responsible_member_id,
        }
    }
}
