/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePermissionSetDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
}

impl CreatePermissionSetDto {
    pub fn new(name: String, permissions: Vec<String>) -> CreatePermissionSetDto {
        CreatePermissionSetDto {
            name,
            description: None,
            permissions,
        }
    }
}

