/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateB2BOrderDto {
    /// List of items in the order
    #[serde(rename = "items")]
    pub items: Vec<models::B2BOrderItemDto>,
}

impl CreateB2BOrderDto {
    pub fn new(items: Vec<models::B2BOrderItemDto>) -> CreateB2BOrderDto {
        CreateB2BOrderDto {
            items,
        }
    }
}
