/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoleGroupDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "permissionSetIds", skip_serializing_if = "Option::is_none")]
    pub permission_set_ids: Option<Vec<String>>,
}

impl CreateRoleGroupDto {
    pub fn new(name: String) -> CreateRoleGroupDto {
        CreateRoleGroupDto {
            name,
            description: None,
            permission_set_ids: None,
        }
    }
}

