/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBusinessAccountDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "taxId", skip_serializing_if = "Option::is_none")]
    pub tax_id: Option<String>,
    #[serde(rename = "defaultLocationId", skip_serializing_if = "Option::is_none")]
    pub default_location_id: Option<String>,
}

impl CreateBusinessAccountDto {
    pub fn new(name: String) -> CreateBusinessAccountDto {
        CreateBusinessAccountDto {
            name,
            tax_id: None,
            default_location_id: None,
        }
    }
}

