/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProductDto {
    /// The name of the product
    #[serde(rename = "name")]
    pub name: String,
    /// Product description
    #[serde(rename = "description")]
    pub description: String,
    /// Base price of the product
    #[serde(rename = "price")]
    pub price: f64,
    /// Stock Keeping Unit
    #[serde(rename = "sku")]
    pub sku: String,
    #[serde(rename = "customFields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Box<models::CmsCustomFieldsDto>>,
}

impl CreateProductDto {
    pub fn new(name: String, description: String, price: f64, sku: String) -> CreateProductDto {
        CreateProductDto {
            name,
            description,
            price,
            sku,
            custom_fields: None,
        }
    }
}
