/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateServiceResourceDto {
    /// Resource name
    #[serde(rename = "name")]
    pub name: String,
    /// Resource type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Is resource active
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl CreateServiceResourceDto {
    pub fn new(name: String) -> CreateServiceResourceDto {
        CreateServiceResourceDto {
            name,
            r#type: None,
            is_active: None,
        }
    }
}
