/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIntegrationDefinitionDto {
    /// Name of integration
    #[serde(rename = "name")]
    pub name: String,
    /// Slug of integration, e.g. shopify
    #[serde(rename = "slug")]
    pub slug: String,
    /// Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Logo URL
    #[serde(rename = "logoUrl", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    /// Category of integration
    #[serde(rename = "category")]
    pub category: Category,
    /// Auth type of integration
    #[serde(rename = "authType")]
    pub auth_type: AuthType,
    /// Is this integration active and connectable
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl CreateIntegrationDefinitionDto {
    pub fn new(name: String, slug: String, category: Category, auth_type: AuthType) -> CreateIntegrationDefinitionDto {
        CreateIntegrationDefinitionDto {
            name,
            slug,
            description: None,
            logo_url: None,
            category,
            auth_type,
            is_active: None,
        }
    }
}
/// Category of integration
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Category {
    #[serde(rename = "E_COMMERCE")]
    ECommerce,
    #[serde(rename = "ACCOUNTING")]
    Accounting,
    #[serde(rename = "MARKETING")]
    Marketing,
    #[serde(rename = "PAYMENT_GATEWAY")]
    PaymentGateway,
    #[serde(rename = "CRM")]
    Crm,
    #[serde(rename = "COMMUNICATION")]
    Communication,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for Category {
    fn default() -> Category {
        Self::ECommerce
    }
}
/// Auth type of integration
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthType {
    #[serde(rename = "API_KEY")]
    ApiKey,
    #[serde(rename = "OAUTH2")]
    Oauth2,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for AuthType {
    fn default() -> AuthType {
        Self::ApiKey
    }
}

