/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTransferDto {
    #[serde(rename = "fromLocationId")]
    pub from_location_id: String,
    #[serde(rename = "toLocationId")]
    pub to_location_id: String,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "items")]
    pub items: Vec<models::CreateTransferItemDto>,
}

impl CreateTransferDto {
    pub fn new(from_location_id: String, to_location_id: String, items: Vec<models::CreateTransferItemDto>) -> CreateTransferDto {
        CreateTransferDto {
            from_location_id,
            to_location_id,
            priority: None,
            notes: None,
            items,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "LOW")]
    Low,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "HIGH")]
    High,
    #[serde(rename = "URGENT")]
    Urgent,
}

impl Default for Priority {
    fn default() -> Priority {
        Self::Low
    }
}

