/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationDto {
    /// The name of the organization
    #[serde(rename = "name")]
    pub name: String,
    /// The unique slug of the organization
    #[serde(rename = "slug")]
    pub slug: String,
    /// Logo URL
    #[serde(rename = "logo", skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
    /// Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CreateOrganizationDto {
    pub fn new(name: String, slug: String) -> CreateOrganizationDto {
        CreateOrganizationDto {
            name,
            slug,
            logo: None,
            description: None,
        }
    }
}
