/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSetupKeyDto {
    /// Human-readable name for the device
    #[serde(rename = "name")]
    pub name: String,
    /// Human-assigned ID for the device (e.g., POS-001)
    #[serde(rename = "deviceId")]
    pub device_id: String,
    /// Expiry in days
    #[serde(rename = "expiresInDays", skip_serializing_if = "Option::is_none")]
    pub expires_in_days: Option<f64>,
}

impl CreateSetupKeyDto {
    pub fn new(name: String, device_id: String) -> CreateSetupKeyDto {
        CreateSetupKeyDto {
            name,
            device_id,
            expires_in_days: None,
        }
    }
}

