/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrmNoteResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "createdById")]
    pub created_by_id: serde_json::Value,
    #[serde(rename = "timelineDate")]
    pub timeline_date: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CrmNoteResponseDto {
    pub fn new(id: String, record_id: String, content: String, created_by_id: serde_json::Value, timeline_date: chrono::DateTime<chrono::FixedOffset>, created_at: chrono::DateTime<chrono::FixedOffset>) -> CrmNoteResponseDto {
        CrmNoteResponseDto {
            id,
            record_id,
            content,
            created_by_id,
            timeline_date,
            created_at,
        }
    }
}
