/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DepartmentResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "headId", skip_serializing_if = "Option::is_none")]
    pub head_id: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl DepartmentResponseDto {
    pub fn new(id: String, name: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> DepartmentResponseDto {
        DepartmentResponseDto {
            id,
            name,
            description: None,
            head_id: None,
            created_at,
        }
    }
}
