/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FavoriteResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "productId")]
    pub product_id: String,
    #[serde(rename = "customerId")]
    pub customer_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl FavoriteResponseDto {
    pub fn new(id: String, product_id: String, customer_id: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> FavoriteResponseDto {
        FavoriteResponseDto {
            id,
            product_id,
            customer_id,
            created_at,
        }
    }
}

