/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvitationResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "inviterId")]
    pub inviter_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl InvitationResponseDto {
    pub fn new(id: String, email: String, role: Role, status: Status, expires_at: chrono::DateTime<chrono::FixedOffset>, inviter_id: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> InvitationResponseDto {
        InvitationResponseDto {
            id,
            email,
            role,
            status,
            expires_at,
            inviter_id,
            created_at,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "OWNER")]
    Owner,
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "MANAGER")]
    Manager,
    #[serde(rename = "EMPLOYEE")]
    Employee,
    #[serde(rename = "CASHIER")]
    Cashier,
    #[serde(rename = "REPORTER")]
    Reporter,
    #[serde(rename = "GUEST")]
    Guest,
}

impl Default for Role {
    fn default() -> Role {
        Self::Owner
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "ACCEPTED")]
    Accepted,
    #[serde(rename = "DECLINED")]
    Declined,
    #[serde(rename = "EXPIRED")]
    Expired,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}
