/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkOrganizationDto {
    /// The internal ID of the standalone device
    #[serde(rename = "deviceId")]
    pub device_id: String,
    /// The ID of the organization to link to
    #[serde(rename = "organizationId")]
    pub organization_id: String,
}

impl LinkOrganizationDto {
    pub fn new(device_id: String, organization_id: String) -> LinkOrganizationDto {
        LinkOrganizationDto {
            device_id,
            organization_id,
        }
    }
}
