/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthClientResponseDto {
    /// Internal ID
    #[serde(rename = "id")]
    pub id: String,
    /// Public OAuth Client ID
    #[serde(rename = "clientId")]
    pub client_id: String,
    /// OAuth Client Secret (returned on creation)
    #[serde(rename = "clientSecret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// Name of the application
    #[serde(rename = "name")]
    pub name: String,
    /// Icon URL
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    /// Homepage URI
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// Redirect URIs
    #[serde(rename = "redirectUris")]
    pub redirect_uris: Vec<String>,
    /// Public client flag
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    /// Skip consent flag
    #[serde(rename = "skipConsent", skip_serializing_if = "Option::is_none")]
    pub skip_consent: Option<bool>,
    /// Creation date
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Last update date
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl OAuthClientResponseDto {
    pub fn new(id: String, client_id: String, name: String, redirect_uris: Vec<String>, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> OAuthClientResponseDto {
        OAuthClientResponseDto {
            id,
            client_id,
            client_secret: None,
            name,
            icon: None,
            uri: None,
            redirect_uris,
            public: None,
            skip_consent: None,
            created_at,
            updated_at,
        }
    }
}

