/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedB2BCatalogDto {
    #[serde(rename = "data")]
    pub data: Vec<models::B2BCatalogProductDto>,
    #[serde(rename = "meta")]
    pub meta: Box<models::PaginationMetaDto>,
}

impl PaginatedB2BCatalogDto {
    pub fn new(data: Vec<models::B2BCatalogProductDto>, meta: models::PaginationMetaDto) -> PaginatedB2BCatalogDto {
        PaginatedB2BCatalogDto {
            data,
            meta: Box::new(meta),
        }
    }
}
