/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationMetaDto {
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "limit")]
    pub limit: f64,
    #[serde(rename = "offset")]
    pub offset: f64,
    #[serde(rename = "nextCursor")]
    pub next_cursor: String,
}

impl PaginationMetaDto {
    pub fn new(total: f64, limit: f64, offset: f64, next_cursor: String) -> PaginationMetaDto {
        PaginationMetaDto {
            total,
            limit,
            offset,
            next_cursor,
        }
    }
}

