/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessSaleDto {
    /// List of physical product variants purchased
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::SaleItemDto>>,
    /// List of services purchased (Option A with bookingId or Option C without)
    #[serde(rename = "serviceItems", skip_serializing_if = "Option::is_none")]
    pub service_items: Option<Vec<models::SaleServiceItemDto>>,
    /// List of payments applied to this transaction
    #[serde(rename = "payments")]
    pub payments: Vec<models::SalePaymentDto>,
    /// Generic discount amount applied to the overall transaction
    #[serde(rename = "discountAmount", skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<f64>,
    /// Optional customer phone number (auto-creates or links customer)
    #[serde(rename = "customerPhone", skip_serializing_if = "Option::is_none")]
    pub customer_phone: Option<String>,
    /// Optional transaction notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Optional loyalty voucher code to apply discount
    #[serde(rename = "loyaltyVoucherCode", skip_serializing_if = "Option::is_none")]
    pub loyalty_voucher_code: Option<String>,
}

impl ProcessSaleDto {
    pub fn new(payments: Vec<models::SalePaymentDto>) -> ProcessSaleDto {
        ProcessSaleDto {
            items: None,
            service_items: None,
            payments,
            discount_amount: None,
            customer_phone: None,
            notes: None,
            loyalty_voucher_code: None,
        }
    }
}
