/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<serde_json::Value>,
    #[serde(rename = "sku")]
    pub sku: String,
    #[serde(rename = "retailPrice", deserialize_with = "Option::deserialize")]
    pub retail_price: Option<serde_json::Value>,
    #[serde(rename = "images")]
    pub images: Vec<String>,
    #[serde(rename = "category")]
    pub category: Box<models::ProductCategoryResponseDto>,
    #[serde(rename = "slug", deserialize_with = "Option::deserialize")]
    pub slug: Option<serde_json::Value>,
    #[serde(rename = "variants", skip_serializing_if = "Option::is_none")]
    pub variants: Option<Vec<models::ProductVariantResponseDto>>,
    #[serde(rename = "customFields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Box<models::CmsCustomFieldsDto>>,
    #[serde(rename = "brand", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand: Option<Option<serde_json::Value>>,
    #[serde(rename = "rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Option<serde_json::Value>>,
    #[serde(rename = "isNew", skip_serializing_if = "Option::is_none")]
    pub is_new: Option<bool>,
    #[serde(rename = "detailedDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub detailed_description: Option<Option<serde_json::Value>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "isFeatured", skip_serializing_if = "Option::is_none")]
    pub is_featured: Option<bool>,
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "pointsOnPurchase", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub points_on_purchase: Option<Option<serde_json::Value>>,
    #[serde(rename = "reviews", skip_serializing_if = "Option::is_none")]
    pub reviews: Option<Vec<models::ProductReviewResponseDto>>,
    #[serde(rename = "favoritesCount", skip_serializing_if = "Option::is_none")]
    pub favorites_count: Option<f64>,
    #[serde(rename = "favouritesCount", skip_serializing_if = "Option::is_none")]
    pub favourites_count: Option<f64>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ProductMetaDto>>,
}

impl ProductResponseDto {
    pub fn new(id: String, name: String, description: Option<serde_json::Value>, sku: String, retail_price: Option<serde_json::Value>, images: Vec<String>, category: models::ProductCategoryResponseDto, slug: Option<serde_json::Value>) -> ProductResponseDto {
        ProductResponseDto {
            id,
            name,
            description,
            sku,
            retail_price,
            images,
            category: Box::new(category),
            slug,
            variants: None,
            custom_fields: None,
            brand: None,
            rating: None,
            is_new: None,
            detailed_description: None,
            tags: None,
            is_featured: None,
            is_active: None,
            points_on_purchase: None,
            reviews: None,
            favorites_count: None,
            favourites_count: None,
            meta: None,
        }
    }
}
