/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductReviewResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "customer")]
    pub customer: Box<models::ProductReviewCustomerDto>,
    #[serde(rename = "rating")]
    pub rating: f64,
    #[serde(rename = "comment", deserialize_with = "Option::deserialize")]
    pub comment: Option<serde_json::Value>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl ProductReviewResponseDto {
    pub fn new(id: String, customer: models::ProductReviewCustomerDto, rating: f64, comment: Option<serde_json::Value>, created_at: String) -> ProductReviewResponseDto {
        ProductReviewResponseDto {
            id,
            customer: Box::new(customer),
            rating,
            comment,
            created_at,
        }
    }
}
