/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductMetaDto {
    #[serde(rename = "averageRating", skip_serializing_if = "Option::is_none")]
    pub average_rating: Option<f64>,
    #[serde(rename = "reviewCount", skip_serializing_if = "Option::is_none")]
    pub review_count: Option<f64>,
}

impl ProductMetaDto {
    pub fn new() -> ProductMetaDto {
        ProductMetaDto {
            average_rating: None,
            review_count: None,
        }
    }
}
