/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReconcilePodDto {
    #[serde(rename = "fulfillmentId")]
    pub fulfillment_id: String,
    #[serde(rename = "outcome")]
    pub outcome: Outcome,
    #[serde(rename = "quantityDelivered", skip_serializing_if = "Option::is_none")]
    pub quantity_delivered: Option<f64>,
    #[serde(rename = "proofOfDeliveryUrl", skip_serializing_if = "Option::is_none")]
    pub proof_of_delivery_url: Option<String>,
    #[serde(rename = "receivedBy", skip_serializing_if = "Option::is_none")]
    pub received_by: Option<String>,
    #[serde(rename = "failureReason", skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
}

impl ReconcilePodDto {
    pub fn new(fulfillment_id: String, outcome: Outcome) -> ReconcilePodDto {
        ReconcilePodDto {
            fulfillment_id,
            outcome,
            quantity_delivered: None,
            proof_of_delivery_url: None,
            received_by: None,
            failure_reason: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Outcome {
    #[serde(rename = "DELIVERED")]
    Delivered,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "PARTIAL")]
    Partial,
}

impl Default for Outcome {
    fn default() -> Outcome {
        Self::Delivered
    }
}
