/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedeemRewardDto {
    /// The ID of the customer
    #[serde(rename = "customerId")]
    pub customer_id: String,
    /// The ID of the reward to redeem
    #[serde(rename = "rewardId")]
    pub reward_id: String,
}

impl RedeemRewardDto {
    pub fn new(customer_id: String, reward_id: String) -> RedeemRewardDto {
        RedeemRewardDto {
            customer_id,
            reward_id,
        }
    }
}
