/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterPettyCashDto {
    /// Description of the expense
    #[serde(rename = "description")]
    pub description: String,
    /// Amount of the expense
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "paymentMethod")]
    pub payment_method: PaymentMethod,
    #[serde(rename = "pettyCashFundId", skip_serializing_if = "Option::is_none")]
    pub petty_cash_fund_id: Option<String>,
    #[serde(rename = "receiptUrl", skip_serializing_if = "Option::is_none")]
    pub receipt_url: Option<String>,
}

impl RegisterPettyCashDto {
    pub fn new(description: String, amount: f64, payment_method: PaymentMethod) -> RegisterPettyCashDto {
        RegisterPettyCashDto {
            description,
            amount,
            payment_method,
            petty_cash_fund_id: None,
            receipt_url: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentMethod {
    #[serde(rename = "CASH")]
    Cash,
    #[serde(rename = "CREDIT")]
    Credit,
    #[serde(rename = "CARD")]
    Card,
    #[serde(rename = "MOBILE_PAYMENT")]
    MobilePayment,
    #[serde(rename = "MPESA_C2B")]
    MpesaC2B,
    #[serde(rename = "BANK_TRANSFER")]
    BankTransfer,
    #[serde(rename = "CHEQUE")]
    Cheque,
    #[serde(rename = "STORE_CREDIT")]
    StoreCredit,
    #[serde(rename = "GIFT_CARD")]
    GiftCard,
    #[serde(rename = "LOYALTY_POINTS")]
    LoyaltyPoints,
    #[serde(rename = "ON_ACCOUNT")]
    OnAccount,
    #[serde(rename = "MPESA")]
    Mpesa,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for PaymentMethod {
    fn default() -> PaymentMethod {
        Self::Cash
    }
}
