/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SalePaymentDto {
    /// Payment method (e.g. CASH, CARD, MPESA)
    #[serde(rename = "method")]
    pub method: String,
    /// Payment amount
    #[serde(rename = "amount")]
    pub amount: f64,
    /// Optional gateway transaction reference or check number
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<String>,
}

impl SalePaymentDto {
    pub fn new(method: String, amount: f64) -> SalePaymentDto {
        SalePaymentDto {
            method,
            amount,
            reference: None,
        }
    }
}

