/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShipTransferItemDto {
    #[serde(rename = "transferItemId")]
    pub transfer_item_id: String,
    #[serde(rename = "shippedQuantity")]
    pub shipped_quantity: f64,
    #[serde(rename = "stockBatchId", skip_serializing_if = "Option::is_none")]
    pub stock_batch_id: Option<String>,
}

impl ShipTransferItemDto {
    pub fn new(transfer_item_id: String, shipped_quantity: f64) -> ShipTransferItemDto {
        ShipTransferItemDto {
            transfer_item_id,
            shipped_quantity,
            stock_batch_id: None,
        }
    }
}

