/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRequestDto {
    /// The Client ID provided during provisioning or registration
    #[serde(rename = "clientId")]
    pub client_id: String,
    /// The Client Secret (optional for client devices like POS/Bakery)
    #[serde(rename = "clientSecret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
}

impl TokenRequestDto {
    pub fn new(client_id: String) -> TokenRequestDto {
        TokenRequestDto {
            client_id,
            client_secret: None,
        }
    }
}

