/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSubscriptionDto {
    /// Slug of the tier / plan
    #[serde(rename = "tierSlug")]
    pub tier_slug: String,
    /// Dodo Customer ID
    #[serde(rename = "dodoCustomerId", skip_serializing_if = "Option::is_none")]
    pub dodo_customer_id: Option<String>,
    /// Dodo Subscription ID
    #[serde(rename = "dodoSubscriptionId", skip_serializing_if = "Option::is_none")]
    pub dodo_subscription_id: Option<String>,
    /// Dodo Price ID
    #[serde(rename = "dodoPriceId", skip_serializing_if = "Option::is_none")]
    pub dodo_price_id: Option<String>,
    /// Dodo Subscription end period
    #[serde(rename = "dodoCurrentPeriodEnd", skip_serializing_if = "Option::is_none")]
    pub dodo_current_period_end: Option<String>,
}

impl UpdateSubscriptionDto {
    pub fn new(tier_slug: String) -> UpdateSubscriptionDto {
        UpdateSubscriptionDto {
            tier_slug,
            dodo_customer_id: None,
            dodo_subscription_id: None,
            dodo_price_id: None,
            dodo_current_period_end: None,
        }
    }
}

