/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateIntegrationDefinitionDto {
    /// Name of integration
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Slug of integration
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Logo URL
    #[serde(rename = "logoUrl", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<String>,
    /// Category of integration
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Category>,
    /// Auth type of integration
    #[serde(rename = "authType", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<AuthType>,
    /// Is this integration active and connectable
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl UpdateIntegrationDefinitionDto {
    pub fn new() -> UpdateIntegrationDefinitionDto {
        UpdateIntegrationDefinitionDto {
            name: None,
            slug: None,
            description: None,
            logo_url: None,
            category: None,
            auth_type: None,
            is_active: None,
        }
    }
}
/// Category of integration
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Category {
    #[serde(rename = "E_COMMERCE")]
    ECommerce,
    #[serde(rename = "ACCOUNTING")]
    Accounting,
    #[serde(rename = "MARKETING")]
    Marketing,
    #[serde(rename = "PAYMENT_GATEWAY")]
    PaymentGateway,
    #[serde(rename = "CRM")]
    Crm,
    #[serde(rename = "COMMUNICATION")]
    Communication,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for Category {
    fn default() -> Category {
        Self::ECommerce
    }
}
/// Auth type of integration
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthType {
    #[serde(rename = "API_KEY")]
    ApiKey,
    #[serde(rename = "OAUTH2")]
    Oauth2,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for AuthType {
    fn default() -> AuthType {
        Self::ApiKey
    }
}
