/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSupplierProductDto {
    /// New cost price
    #[serde(rename = "costPrice", skip_serializing_if = "Option::is_none")]
    pub cost_price: Option<f64>,
    /// Supplier-specific SKU
    #[serde(rename = "supplierSku", skip_serializing_if = "Option::is_none")]
    pub supplier_sku: Option<String>,
    /// Is this the preferred supplier for this product/variant?
    #[serde(rename = "isPreferred", skip_serializing_if = "Option::is_none")]
    pub is_preferred: Option<bool>,
}

impl UpdateSupplierProductDto {
    pub fn new() -> UpdateSupplierProductDto {
        UpdateSupplierProductDto {
            cost_price: None,
            supplier_sku: None,
            is_preferred: None,
        }
    }
}
