/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCrmRecordDto {
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "ownerId", skip_serializing_if = "Option::is_none")]
    pub owner_id: Option<String>,
}

impl UpdateCrmRecordDto {
    pub fn new(data: serde_json::Value) -> UpdateCrmRecordDto {
        UpdateCrmRecordDto {
            data,
            owner_id: None,
        }
    }
}

