/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateVoucherDto {
    /// The voucher code to validate
    #[serde(rename = "code")]
    pub code: String,
    /// The ID of the customer
    #[serde(rename = "customerId")]
    pub customer_id: String,
}

impl ValidateVoucherDto {
    pub fn new(code: String, customer_id: String) -> ValidateVoucherDto {
        ValidateVoucherDto {
            code,
            customer_id,
        }
    }
}
