/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyOtpDto {
    /// Phone number used
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// Email address used
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// OTP code
    #[serde(rename = "code")]
    pub code: String,
}

impl VerifyOtpDto {
    pub fn new(code: String) -> VerifyOtpDto {
        VerifyOtpDto {
            phone_number: None,
            email: None,
            code,
        }
    }
}

