/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "events")]
    pub events: Vec<String>,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl WebhookResponseDto {
    pub fn new(id: String, name: String, url: String, events: Vec<String>, secret: String) -> WebhookResponseDto {
        WebhookResponseDto {
            id,
            name,
            url,
            events,
            secret,
        }
    }
}

