// ============================================================
// SCRYME CRM — MOCK DATA
// ============================================================

export type CustomerStatus = 'Active' | 'Inactive' | 'VIP' | 'Lead';
export type CustomerType = 'B2C' | 'B2B' | 'Enterprise';
export type InvoiceStatus = 'Draft' | 'Sent' | 'Paid' | 'Overdue' | 'Void';
export type DeliveryStatus = 'Pending' | 'In Transit' | 'Delivered' | 'Cancelled' | 'Failed';
export type OrderStatus = 'Pending' | 'Processing' | 'Completed' | 'Cancelled' | 'Refunded';
export type OrderChannel = 'POS' | 'Online' | 'B2B' | 'Phone';
export type ConversationChannel = 'Phone' | 'Email' | 'In-Person' | 'Chat' | 'Video Call';
export type ConversationDirection = 'Inbound' | 'Outbound';
export type FollowUpPriority = 'High' | 'Medium' | 'Low';
export type FollowUpStatus = 'Pending' | 'Completed' | 'Overdue' | 'Cancelled';

export interface Note {
  id: string;
  customerId: string;
  content: string;
  author: string;
  authorInitials: string;
  createdAt: string;
  pinned?: boolean;
}

export interface Delivery {
  id: string;
  customerId: string;
  orderRef: string;
  items: string;
  address: string;
  status: DeliveryStatus;
  driver: string;
  scheduledDate: string;
  deliveredDate?: string;
  trackingNumber: string;
}

export interface Invoice {
  id: string;
  customerId: string;
  invoiceNumber: string;
  date: string;
  dueDate: string;
  items: string;
  subtotal: number;
  tax: number;
  total: number;
  amountPaid: number;
  status: InvoiceStatus;
}

export interface Order {
  id: string;
  customerId: string;
  orderNumber: string;
  type: OrderChannel;
  date: string;
  itemCount: number;
  items: string;
  subtotal: number;
  discount: number;
  tax: number;
  total: number;
  status: OrderStatus;
  channel: string;
}

export interface Conversation {
  id: string;
  customerId: string;
  channel: ConversationChannel;
  direction: ConversationDirection;
  date: string;
  subject: string;
  summary: string;
  loggedBy: string;
  loggedByInitials: string;
  duration?: string;
}

export interface FollowUp {
  id: string;
  customerId: string;
  title: string;
  description: string;
  dueDate: string;
  priority: FollowUpPriority;
  status: FollowUpStatus;
  assignedTo: string;
  assignedToInitials: string;
  completedDate?: string;
}

export interface Customer {
  id: string;
  name: string;
  email: string;
  phone: string;
  company: string;
  type: CustomerType;
  status: CustomerStatus;
  tags: string[];
  loyaltyPoints: number;
  address: string;
  city: string;
  country: string;
  avatar?: string;
  website?: string;
  industry: string;
  accountManager: string;
  accountManagerInitials: string;
  createdAt: string;
  lastActivity: string;
  totalRevenue: number;
  totalOrders: number;
  openInvoices: number;
  healthScore: number; // 0–100
  notes: Note[];
  deliveries: Delivery[];
  invoices: Invoice[];
  orders: Order[];
  conversations: Conversation[];
  followUps: FollowUp[];
}

// ----------------------------------------------------------------
// CUSTOMERS
// ----------------------------------------------------------------

export const customers: Customer[] = [
  {
    id: 'c-001',
    name: 'Evelyn Harper',
    email: 'evelyn.harper@archway.io',
    phone: '+1 (415) 882-3401',
    company: 'Archway Technologies',
    type: 'Enterprise',
    status: 'VIP',
    tags: ['SaaS', 'Tier-1', 'Renewal Due'],
    loyaltyPoints: 14800,
    address: '500 Market St, Suite 2200',
    city: 'San Francisco',
    country: 'USA',
    website: 'archway.io',
    industry: 'Technology',
    accountManager: 'Marcus Reid',
    accountManagerInitials: 'MR',
    createdAt: '2021-03-14',
    lastActivity: '2025-05-20',
    totalRevenue: 487500,
    totalOrders: 38,
    openInvoices: 3,
    healthScore: 92,
    notes: [
      {
        id: 'n-001-1',
        customerId: 'c-001',
        content: 'Evelyn confirmed interest in expanding their seat count from 200 to 500 during Q3. She mentioned budget was already approved internally — follow up with a revised proposal.',
        author: 'Marcus Reid',
        authorInitials: 'MR',
        createdAt: '2025-05-18T10:22:00Z',
        pinned: true,
      },
      {
        id: 'n-001-2',
        customerId: 'c-001',
        content: 'Positive NPS response received — score of 9/10. Mentioned onboarding was "best they had experienced." Shared feedback with the product team.',
        author: 'Sarah Kim',
        authorInitials: 'SK',
        createdAt: '2025-04-30T14:15:00Z',
      },
      {
        id: 'n-001-3',
        customerId: 'c-001',
        content: 'Contract renewal negotiation ongoing. Legal team reviewing SLA amendments. Expected close by end of June.',
        author: 'Marcus Reid',
        authorInitials: 'MR',
        createdAt: '2025-04-12T09:00:00Z',
      },
    ],
    deliveries: [
      {
        id: 'd-001-1',
        customerId: 'c-001',
        orderRef: 'ORD-2025-0412',
        items: 'Enterprise License Docs x1, USB Keys x5',
        address: '500 Market St, Suite 2200, San Francisco',
        status: 'Delivered',
        driver: 'FedEx Priority',
        scheduledDate: '2025-04-20',
        deliveredDate: '2025-04-20',
        trackingNumber: 'FX-8830291044',
      },
      {
        id: 'd-001-2',
        customerId: 'c-001',
        orderRef: 'ORD-2025-0519',
        items: 'Hardware Tokens x20',
        address: '500 Market St, Suite 2200, San Francisco',
        status: 'In Transit',
        driver: 'UPS Express',
        scheduledDate: '2025-05-25',
        trackingNumber: 'UPS-1Z9938203',
      },
    ],
    invoices: [
      {
        id: 'inv-001-1',
        customerId: 'c-001',
        invoiceNumber: 'INV-2025-0041',
        date: '2025-05-01',
        dueDate: '2025-05-31',
        items: 'Annual Enterprise License (500 seats)',
        subtotal: 120000,
        tax: 10800,
        total: 130800,
        amountPaid: 130800,
        status: 'Paid',
      },
      {
        id: 'inv-001-2',
        customerId: 'c-001',
        invoiceNumber: 'INV-2025-0087',
        date: '2025-05-15',
        dueDate: '2025-06-14',
        items: 'Professional Services — Q2 Implementation',
        subtotal: 28000,
        tax: 2520,
        total: 30520,
        amountPaid: 0,
        status: 'Sent',
      },
      {
        id: 'inv-001-3',
        customerId: 'c-001',
        invoiceNumber: 'INV-2025-0102',
        date: '2025-05-22',
        dueDate: '2025-06-05',
        items: 'Hardware Tokens x20',
        subtotal: 4800,
        tax: 432,
        total: 5232,
        amountPaid: 0,
        status: 'Overdue',
      },
    ],
    orders: [
      {
        id: 'o-001-1',
        customerId: 'c-001',
        orderNumber: 'ORD-2025-0412',
        type: 'B2B',
        date: '2025-04-12',
        itemCount: 2,
        items: 'Enterprise License, Hardware Tokens',
        subtotal: 124800,
        discount: 6240,
        tax: 10584,
        total: 129144,
        status: 'Completed',
        channel: 'Sales Portal',
      },
      {
        id: 'o-001-2',
        customerId: 'c-001',
        orderNumber: 'ORD-2025-0519',
        type: 'B2B',
        date: '2025-05-19',
        itemCount: 1,
        items: 'Professional Services Package',
        subtotal: 28000,
        discount: 0,
        tax: 2520,
        total: 30520,
        status: 'Processing',
        channel: 'Sales Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-001-1',
        customerId: 'c-001',
        channel: 'Video Call',
        direction: 'Inbound',
        date: '2025-05-20T14:00:00Z',
        subject: 'Q3 Expansion Planning',
        summary: 'Evelyn walked us through their internal roadmap. They plan to onboard 300 additional users in Q3 and want a phased pricing structure. Agreed to send a revised proposal by EOW.',
        loggedBy: 'Marcus Reid',
        loggedByInitials: 'MR',
        duration: '52 min',
      },
      {
        id: 'conv-001-2',
        customerId: 'c-001',
        channel: 'Email',
        direction: 'Outbound',
        date: '2025-05-14T09:30:00Z',
        subject: 'Invoice INV-2025-0087 Follow-up',
        summary: 'Sent payment reminder for professional services invoice. Evelyn confirmed receipt and said finance would process within the week.',
        loggedBy: 'Sarah Kim',
        loggedByInitials: 'SK',
      },
      {
        id: 'conv-001-3',
        customerId: 'c-001',
        channel: 'Phone',
        direction: 'Inbound',
        date: '2025-04-28T11:00:00Z',
        subject: 'Support Escalation — SSO Integration',
        summary: 'Reported issue with SAML SSO configuration after recent update. Escalated to engineering. Issue resolved same day.',
        loggedBy: 'Dev Support',
        loggedByInitials: 'DS',
        duration: '18 min',
      },
    ],
    followUps: [
      {
        id: 'fu-001-1',
        customerId: 'c-001',
        title: 'Send Q3 Expansion Proposal',
        description: 'Prepare and send revised pricing for 500-seat expansion. Include phased onboarding timeline.',
        dueDate: '2025-05-28',
        priority: 'High',
        status: 'Pending',
        assignedTo: 'Marcus Reid',
        assignedToInitials: 'MR',
      },
      {
        id: 'fu-001-2',
        customerId: 'c-001',
        title: 'Collect Overdue Invoice INV-2025-0102',
        description: 'Follow up with accounts payable regarding overdue hardware token invoice.',
        dueDate: '2025-05-26',
        priority: 'High',
        status: 'Overdue',
        assignedTo: 'Sarah Kim',
        assignedToInitials: 'SK',
      },
    ],
  },
  {
    id: 'c-002',
    name: 'James Okafor',
    email: 'james.okafor@novabloom.co',
    phone: '+44 20 7946 0201',
    company: 'NovaBloom Co.',
    type: 'B2B',
    status: 'Active',
    tags: ['Retail', 'Growth Account'],
    loyaltyPoints: 7320,
    address: '12 Canary Wharf, Level 8',
    city: 'London',
    country: 'UK',
    website: 'novabloom.co',
    industry: 'Retail',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2022-07-01',
    lastActivity: '2025-05-17',
    totalRevenue: 213400,
    totalOrders: 22,
    openInvoices: 1,
    healthScore: 78,
    notes: [
      {
        id: 'n-002-1',
        customerId: 'c-002',
        content: 'James expressed frustration with Q1 delivery delays. Offered 5% credit on next order. Relationship is good overall but we need to improve logistics SLA for UK customers.',
        author: 'Sarah Kim',
        authorInitials: 'SK',
        createdAt: '2025-03-22T10:00:00Z',
        pinned: true,
      },
      {
        id: 'n-002-2',
        customerId: 'c-002',
        content: 'Interested in new inventory management module. Scheduled product demo for June 3.',
        author: 'Alex Torres',
        authorInitials: 'AT',
        createdAt: '2025-05-10T14:30:00Z',
      },
    ],
    deliveries: [
      {
        id: 'd-002-1',
        customerId: 'c-002',
        orderRef: 'ORD-2025-0310',
        items: 'Product Catalogue Binders x50',
        address: '12 Canary Wharf, Level 8, London',
        status: 'Delivered',
        driver: 'DHL Express',
        scheduledDate: '2025-03-18',
        deliveredDate: '2025-03-22',
        trackingNumber: 'DHL-120483920',
      },
      {
        id: 'd-002-2',
        customerId: 'c-002',
        orderRef: 'ORD-2025-0501',
        items: 'POS Hardware Kit x3',
        address: '12 Canary Wharf, Level 8, London',
        status: 'Pending',
        driver: 'UPS Standard',
        scheduledDate: '2025-05-28',
        trackingNumber: 'UPS-1Z77239010',
      },
    ],
    invoices: [
      {
        id: 'inv-002-1',
        customerId: 'c-002',
        invoiceNumber: 'INV-2025-0033',
        date: '2025-03-01',
        dueDate: '2025-03-31',
        items: 'Q1 Software Subscription',
        subtotal: 18000,
        tax: 3600,
        total: 21600,
        amountPaid: 21600,
        status: 'Paid',
      },
      {
        id: 'inv-002-2',
        customerId: 'c-002',
        invoiceNumber: 'INV-2025-0091',
        date: '2025-05-01',
        dueDate: '2025-05-31',
        items: 'POS Hardware Kit x3 + Installation',
        subtotal: 9400,
        tax: 1880,
        total: 11280,
        amountPaid: 0,
        status: 'Sent',
      },
    ],
    orders: [
      {
        id: 'o-002-1',
        customerId: 'c-002',
        orderNumber: 'ORD-2025-0310',
        type: 'B2B',
        date: '2025-03-10',
        itemCount: 1,
        items: 'Product Catalogue Binders',
        subtotal: 1200,
        discount: 60,
        tax: 228,
        total: 1368,
        status: 'Completed',
        channel: 'Account Portal',
      },
      {
        id: 'o-002-2',
        customerId: 'c-002',
        orderNumber: 'ORD-2025-0501',
        type: 'B2B',
        date: '2025-05-01',
        itemCount: 2,
        items: 'POS Hardware Kit, Installation Service',
        subtotal: 9400,
        discount: 0,
        tax: 1880,
        total: 11280,
        status: 'Processing',
        channel: 'Account Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-002-1',
        customerId: 'c-002',
        channel: 'Phone',
        direction: 'Inbound',
        date: '2025-03-22T09:00:00Z',
        subject: 'Delivery Delay Complaint',
        summary: 'James called to complain about delivery arriving 4 days late for March order. Apologized and offered credit. Escalated to logistics team.',
        loggedBy: 'Sarah Kim',
        loggedByInitials: 'SK',
        duration: '22 min',
      },
      {
        id: 'conv-002-2',
        customerId: 'c-002',
        channel: 'Email',
        direction: 'Outbound',
        date: '2025-05-10T11:00:00Z',
        subject: 'Inventory Module Demo Invitation',
        summary: 'Sent calendar invite for June 3 demo. James confirmed attendance.',
        loggedBy: 'Alex Torres',
        loggedByInitials: 'AT',
      },
    ],
    followUps: [
      {
        id: 'fu-002-1',
        customerId: 'c-002',
        title: 'Product Demo — Inventory Module',
        description: 'Host live demo for James and his ops team on June 3.',
        dueDate: '2025-06-03',
        priority: 'Medium',
        status: 'Pending',
        assignedTo: 'Alex Torres',
        assignedToInitials: 'AT',
      },
    ],
  },
  {
    id: 'c-003',
    name: 'Priya Nair',
    email: 'priya.nair@heliosfinance.com',
    phone: '+91 98200 44312',
    company: 'Helios Finance Ltd.',
    type: 'Enterprise',
    status: 'VIP',
    tags: ['FinTech', 'Tier-1', 'High Risk'],
    loyaltyPoints: 21000,
    address: 'Bandra Kurla Complex, G Block',
    city: 'Mumbai',
    country: 'India',
    website: 'heliosfinance.com',
    industry: 'Financial Services',
    accountManager: 'Marcus Reid',
    accountManagerInitials: 'MR',
    createdAt: '2020-11-30',
    lastActivity: '2025-05-19',
    totalRevenue: 892000,
    totalOrders: 61,
    openInvoices: 2,
    healthScore: 88,
    notes: [
      {
        id: 'n-003-1',
        customerId: 'c-003',
        content: 'Regulatory compliance audit scheduled for July. Priya asked for updated SOC 2 Type II report. Requested by June 15 — flag for legal team.',
        author: 'Marcus Reid',
        authorInitials: 'MR',
        createdAt: '2025-05-15T08:30:00Z',
        pinned: true,
      },
      {
        id: 'n-003-2',
        customerId: 'c-003',
        content: 'Interested in AI-powered fraud detection add-on. Wants a pilot before full commitment. Pilot window: August.',
        author: 'Priya Nair',
        authorInitials: 'PN',
        createdAt: '2025-04-20T15:00:00Z',
      },
    ],
    deliveries: [
      {
        id: 'd-003-1',
        customerId: 'c-003',
        orderRef: 'ORD-2025-0210',
        items: 'Compliance Audit Reports x3, Security Keys x10',
        address: 'BKC, G Block, Mumbai',
        status: 'Delivered',
        driver: 'Blue Dart Express',
        scheduledDate: '2025-02-18',
        deliveredDate: '2025-02-19',
        trackingNumber: 'BD-498201933',
      },
    ],
    invoices: [
      {
        id: 'inv-003-1',
        customerId: 'c-003',
        invoiceNumber: 'INV-2025-0020',
        date: '2025-02-01',
        dueDate: '2025-02-28',
        items: 'Enterprise Platform License — Annual',
        subtotal: 240000,
        tax: 43200,
        total: 283200,
        amountPaid: 283200,
        status: 'Paid',
      },
      {
        id: 'inv-003-2',
        customerId: 'c-003',
        invoiceNumber: 'INV-2025-0078',
        date: '2025-04-15',
        dueDate: '2025-05-15',
        items: 'AI Fraud Detection Module — Pilot',
        subtotal: 38000,
        tax: 6840,
        total: 44840,
        amountPaid: 0,
        status: 'Overdue',
      },
      {
        id: 'inv-003-3',
        customerId: 'c-003',
        invoiceNumber: 'INV-2025-0095',
        date: '2025-05-10',
        dueDate: '2025-06-10',
        items: 'SOC 2 Compliance Package',
        subtotal: 12000,
        tax: 2160,
        total: 14160,
        amountPaid: 0,
        status: 'Sent',
      },
    ],
    orders: [
      {
        id: 'o-003-1',
        customerId: 'c-003',
        orderNumber: 'ORD-2025-0210',
        type: 'B2B',
        date: '2025-02-10',
        itemCount: 3,
        items: 'Annual License, Security Keys, Audit Reports',
        subtotal: 252000,
        discount: 12600,
        tax: 43074,
        total: 282474,
        status: 'Completed',
        channel: 'Enterprise Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-003-1',
        customerId: 'c-003',
        channel: 'Video Call',
        direction: 'Inbound',
        date: '2025-05-19T12:00:00Z',
        subject: 'SOC 2 Report & Audit Prep',
        summary: 'Priya reviewed timeline for the July compliance audit. SOC 2 report required by June 15. Legal team will review and send within two weeks.',
        loggedBy: 'Marcus Reid',
        loggedByInitials: 'MR',
        duration: '45 min',
      },
    ],
    followUps: [
      {
        id: 'fu-003-1',
        customerId: 'c-003',
        title: 'Deliver SOC 2 Type II Report',
        description: 'Coordinate with legal team to deliver updated SOC 2 report to Priya by June 15.',
        dueDate: '2025-06-15',
        priority: 'High',
        status: 'Pending',
        assignedTo: 'Marcus Reid',
        assignedToInitials: 'MR',
      },
      {
        id: 'fu-003-2',
        customerId: 'c-003',
        title: 'Chase Overdue Invoice INV-2025-0078',
        description: 'AI fraud detection pilot invoice now overdue. Contact Priya\'s AP team directly.',
        dueDate: '2025-05-22',
        priority: 'High',
        status: 'Overdue',
        assignedTo: 'Sarah Kim',
        assignedToInitials: 'SK',
      },
    ],
  },
  {
    id: 'c-004',
    name: 'Carlos Mendez',
    email: 'carlos.mendez@vistacorp.mx',
    phone: '+52 55 5284 8800',
    company: 'VistaCorp Mexico',
    type: 'B2B',
    status: 'Active',
    tags: ['Manufacturing', 'LATAM'],
    loyaltyPoints: 4800,
    address: 'Av. Insurgentes Sur 1602',
    city: 'Mexico City',
    country: 'Mexico',
    industry: 'Manufacturing',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2023-02-20',
    lastActivity: '2025-05-12',
    totalRevenue: 134200,
    totalOrders: 14,
    openInvoices: 1,
    healthScore: 71,
    notes: [
      {
        id: 'n-004-1',
        customerId: 'c-004',
        content: 'Carlos mentioned interest in bulk pricing for their Monterrey facility. Expects to double order volume in H2 2025.',
        author: 'Alex Torres',
        authorInitials: 'AT',
        createdAt: '2025-05-05T10:00:00Z',
      },
    ],
    deliveries: [
      {
        id: 'd-004-1',
        customerId: 'c-004',
        orderRef: 'ORD-2025-0418',
        items: 'Industrial Control Units x8',
        address: 'Av. Insurgentes Sur 1602, Mexico City',
        status: 'In Transit',
        driver: 'DHL Freight',
        scheduledDate: '2025-05-30',
        trackingNumber: 'DHL-FRGHT-48293',
      },
    ],
    invoices: [
      {
        id: 'inv-004-1',
        customerId: 'c-004',
        invoiceNumber: 'INV-2025-0060',
        date: '2025-04-18',
        dueDate: '2025-05-18',
        items: 'Industrial Control Units x8',
        subtotal: 64000,
        tax: 10240,
        total: 74240,
        amountPaid: 0,
        status: 'Overdue',
      },
    ],
    orders: [
      {
        id: 'o-004-1',
        customerId: 'c-004',
        orderNumber: 'ORD-2025-0418',
        type: 'B2B',
        date: '2025-04-18',
        itemCount: 1,
        items: 'Industrial Control Units x8',
        subtotal: 64000,
        discount: 3200,
        tax: 10240,
        total: 71040,
        status: 'Processing',
        channel: 'Sales Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-004-1',
        customerId: 'c-004',
        channel: 'Phone',
        direction: 'Outbound',
        date: '2025-05-12T16:00:00Z',
        subject: 'Order Status Check',
        summary: 'Called Carlos to confirm shipment of ORD-2025-0418. Shared tracking number. Carlos satisfied with update.',
        loggedBy: 'Alex Torres',
        loggedByInitials: 'AT',
        duration: '8 min',
      },
    ],
    followUps: [
      {
        id: 'fu-004-1',
        customerId: 'c-004',
        title: 'Bulk Pricing Proposal — Monterrey',
        description: 'Prepare tiered bulk pricing sheet for industrial control units for Monterrey facility expansion.',
        dueDate: '2025-06-10',
        priority: 'Medium',
        status: 'Pending',
        assignedTo: 'Alex Torres',
        assignedToInitials: 'AT',
      },
    ],
  },
  {
    id: 'c-005',
    name: 'Amara Osei',
    email: 'amara.osei@greenpath.gh',
    phone: '+233 30 274 5000',
    company: 'GreenPath Logistics',
    type: 'B2C',
    status: 'Active',
    tags: ['Logistics', 'Emerging Market'],
    loyaltyPoints: 3200,
    address: 'Liberation Rd, Airport City',
    city: 'Accra',
    country: 'Ghana',
    industry: 'Logistics',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2023-08-11',
    lastActivity: '2025-04-30',
    totalRevenue: 48900,
    totalOrders: 9,
    openInvoices: 0,
    healthScore: 65,
    notes: [
      {
        id: 'n-005-1',
        customerId: 'c-005',
        content: 'Amara is evaluating alternatives due to currency volatility. Offer USD-locked pricing to retain the account.',
        author: 'Sarah Kim',
        authorInitials: 'SK',
        createdAt: '2025-04-29T09:00:00Z',
        pinned: true,
      },
    ],
    deliveries: [
      {
        id: 'd-005-1',
        customerId: 'c-005',
        orderRef: 'ORD-2025-0401',
        items: 'Fleet Tracker Devices x12',
        address: 'Liberation Rd, Airport City, Accra',
        status: 'Delivered',
        driver: 'Courier Plus GH',
        scheduledDate: '2025-04-10',
        deliveredDate: '2025-04-14',
        trackingNumber: 'CPG-2049183',
      },
    ],
    invoices: [
      {
        id: 'inv-005-1',
        customerId: 'c-005',
        invoiceNumber: 'INV-2025-0055',
        date: '2025-04-01',
        dueDate: '2025-04-30',
        items: 'Fleet Tracker Devices x12',
        subtotal: 9600,
        tax: 1440,
        total: 11040,
        amountPaid: 11040,
        status: 'Paid',
      },
    ],
    orders: [
      {
        id: 'o-005-1',
        customerId: 'c-005',
        orderNumber: 'ORD-2025-0401',
        type: 'Online',
        date: '2025-04-01',
        itemCount: 1,
        items: 'Fleet Tracker Devices x12',
        subtotal: 9600,
        discount: 480,
        tax: 1440,
        total: 10560,
        status: 'Completed',
        channel: 'Web Store',
      },
    ],
    conversations: [
      {
        id: 'conv-005-1',
        customerId: 'c-005',
        channel: 'Email',
        direction: 'Inbound',
        date: '2025-04-29T08:00:00Z',
        subject: 'Pricing Concern',
        summary: 'Amara raised concerns about FX impact on USD pricing. Explained current pricing structure and offered to explore USD-locked contracts.',
        loggedBy: 'Sarah Kim',
        loggedByInitials: 'SK',
      },
    ],
    followUps: [
      {
        id: 'fu-005-1',
        customerId: 'c-005',
        title: 'Send USD-Locked Pricing Options',
        description: 'Prepare and send a pricing sheet with USD-locked annual rates to prevent churn.',
        dueDate: '2025-05-30',
        priority: 'High',
        status: 'Pending',
        assignedTo: 'Sarah Kim',
        assignedToInitials: 'SK',
      },
    ],
  },
  {
    id: 'c-006',
    name: 'Thomas Bergmann',
    email: 'thomas.b@krafwerk.de',
    phone: '+49 89 2143 6700',
    company: 'Kraftwerk Solutions GmbH',
    type: 'Enterprise',
    status: 'VIP',
    tags: ['Engineering', 'DACH', 'Long-term'],
    loyaltyPoints: 18200,
    address: 'Maximilianstraße 35',
    city: 'Munich',
    country: 'Germany',
    industry: 'Engineering',
    accountManager: 'Marcus Reid',
    accountManagerInitials: 'MR',
    createdAt: '2019-06-01',
    lastActivity: '2025-05-21',
    totalRevenue: 1240000,
    totalOrders: 88,
    openInvoices: 1,
    healthScore: 96,
    notes: [
      {
        id: 'n-006-1',
        customerId: 'c-006',
        content: 'Thomas is one of our longest-standing enterprise clients. Very satisfied. Mentioned he will personally recommend Scryme to two other engineering firms in Frankfurt.',
        author: 'Marcus Reid',
        authorInitials: 'MR',
        createdAt: '2025-05-21T11:00:00Z',
        pinned: true,
      },
    ],
    deliveries: [
      {
        id: 'd-006-1',
        customerId: 'c-006',
        orderRef: 'ORD-2025-0503',
        items: 'Custom Hardware Bundle x5',
        address: 'Maximilianstraße 35, Munich',
        status: 'Delivered',
        driver: 'DHL Express DE',
        scheduledDate: '2025-05-10',
        deliveredDate: '2025-05-10',
        trackingNumber: 'DHL-DE-8821930',
      },
    ],
    invoices: [
      {
        id: 'inv-006-1',
        customerId: 'c-006',
        invoiceNumber: 'INV-2025-0070',
        date: '2025-05-01',
        dueDate: '2025-05-30',
        items: 'Annual Enterprise License Renewal',
        subtotal: 300000,
        tax: 57000,
        total: 357000,
        amountPaid: 357000,
        status: 'Paid',
      },
      {
        id: 'inv-006-2',
        customerId: 'c-006',
        invoiceNumber: 'INV-2025-0106',
        date: '2025-05-20',
        dueDate: '2025-06-20',
        items: 'Custom Hardware Bundle x5',
        subtotal: 18500,
        tax: 3515,
        total: 22015,
        amountPaid: 0,
        status: 'Sent',
      },
    ],
    orders: [
      {
        id: 'o-006-1',
        customerId: 'c-006',
        orderNumber: 'ORD-2025-0503',
        type: 'B2B',
        date: '2025-05-03',
        itemCount: 1,
        items: 'Custom Hardware Bundle',
        subtotal: 18500,
        discount: 925,
        tax: 3327,
        total: 20902,
        status: 'Completed',
        channel: 'Enterprise Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-006-1',
        customerId: 'c-006',
        channel: 'In-Person',
        direction: 'Inbound',
        date: '2025-05-21T10:00:00Z',
        subject: 'Annual Business Review',
        summary: 'Thomas visited Munich office for ABR. Very positive meeting. Discussed new product roadmap and upcoming features for H2. Thomas will introduce two new potential clients.',
        loggedBy: 'Marcus Reid',
        loggedByInitials: 'MR',
        duration: '3 hrs',
      },
    ],
    followUps: [
      {
        id: 'fu-006-1',
        customerId: 'c-006',
        title: 'Referral Follow-up — Frankfurt Firms',
        description: 'Contact the two engineering firms Thomas mentioned. Request intro email from Thomas.',
        dueDate: '2025-06-01',
        priority: 'Medium',
        status: 'Pending',
        assignedTo: 'Marcus Reid',
        assignedToInitials: 'MR',
      },
    ],
  },
  {
    id: 'c-007',
    name: 'Lily Zhang',
    email: 'lily.zhang@brightedge.hk',
    phone: '+852 2234 9900',
    company: 'BrightEdge Asia',
    type: 'B2B',
    status: 'Active',
    tags: ['EdTech', 'APAC'],
    loyaltyPoints: 6100,
    address: '18 Harbour Road, Wan Chai',
    city: 'Hong Kong',
    country: 'Hong Kong SAR',
    industry: 'Education Technology',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2022-01-15',
    lastActivity: '2025-05-08',
    totalRevenue: 178000,
    totalOrders: 19,
    openInvoices: 1,
    healthScore: 80,
    notes: [
      {
        id: 'n-007-1',
        customerId: 'c-007',
        content: 'Lily confirmed their Mandarin-language LMS integration is launching in September. They will need dedicated technical support throughout August.',
        author: 'Alex Torres',
        authorInitials: 'AT',
        createdAt: '2025-05-08T13:00:00Z',
      },
    ],
    deliveries: [
      {
        id: 'd-007-1',
        customerId: 'c-007',
        orderRef: 'ORD-2025-0422',
        items: 'Tablet Devices x30, Accessories x30',
        address: '18 Harbour Road, Wan Chai, Hong Kong',
        status: 'Delivered',
        driver: 'SF Express',
        scheduledDate: '2025-04-28',
        deliveredDate: '2025-04-29',
        trackingNumber: 'SF-HK-291038',
      },
    ],
    invoices: [
      {
        id: 'inv-007-1',
        customerId: 'c-007',
        invoiceNumber: 'INV-2025-0066',
        date: '2025-04-22',
        dueDate: '2025-05-22',
        items: 'Tablet Devices x30 + Accessories',
        subtotal: 24000,
        tax: 0,
        total: 24000,
        amountPaid: 24000,
        status: 'Paid',
      },
      {
        id: 'inv-007-2',
        customerId: 'c-007',
        invoiceNumber: 'INV-2025-0098',
        date: '2025-05-08',
        dueDate: '2025-06-08',
        items: 'LMS Integration — Technical Support Package',
        subtotal: 14000,
        tax: 0,
        total: 14000,
        amountPaid: 0,
        status: 'Draft',
      },
    ],
    orders: [
      {
        id: 'o-007-1',
        customerId: 'c-007',
        orderNumber: 'ORD-2025-0422',
        type: 'B2B',
        date: '2025-04-22',
        itemCount: 2,
        items: 'Tablet Devices, Accessories',
        subtotal: 24000,
        discount: 1200,
        tax: 0,
        total: 22800,
        status: 'Completed',
        channel: 'Account Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-007-1',
        customerId: 'c-007',
        channel: 'Chat',
        direction: 'Inbound',
        date: '2025-05-08T10:00:00Z',
        subject: 'LMS Integration Timeline',
        summary: 'Lily confirmed September launch. Requested dedicated technical support in August. Will share project specs by end of May.',
        loggedBy: 'Alex Torres',
        loggedByInitials: 'AT',
      },
    ],
    followUps: [
      {
        id: 'fu-007-1',
        customerId: 'c-007',
        title: 'Finalize August Technical Support Plan',
        description: 'After receiving Lily\'s project specs, create a support schedule for August LMS go-live.',
        dueDate: '2025-06-05',
        priority: 'Medium',
        status: 'Pending',
        assignedTo: 'Alex Torres',
        assignedToInitials: 'AT',
      },
    ],
  },
  {
    id: 'c-008',
    name: 'Rachel Foster',
    email: 'rachel.foster@northlandmed.ca',
    phone: '+1 (604) 882-4430',
    company: 'Northland Medical Group',
    type: 'Enterprise',
    status: 'Active',
    tags: ['Healthcare', 'Compliance'],
    loyaltyPoints: 9400,
    address: '1200 West Georgia St',
    city: 'Vancouver',
    country: 'Canada',
    industry: 'Healthcare',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2021-09-01',
    lastActivity: '2025-05-16',
    totalRevenue: 341000,
    totalOrders: 27,
    openInvoices: 2,
    healthScore: 84,
    notes: [
      {
        id: 'n-008-1',
        customerId: 'c-008',
        content: 'HIPAA compliance renewal required. Rachel expects full documentation package by July 1. Legal must provide updated BAA.',
        author: 'Sarah Kim',
        authorInitials: 'SK',
        createdAt: '2025-05-16T09:00:00Z',
        pinned: true,
      },
    ],
    deliveries: [
      {
        id: 'd-008-1',
        customerId: 'c-008',
        orderRef: 'ORD-2025-0412',
        items: 'Medical Device Trackers x15',
        address: '1200 West Georgia St, Vancouver',
        status: 'Delivered',
        driver: 'Purolator',
        scheduledDate: '2025-04-18',
        deliveredDate: '2025-04-19',
        trackingNumber: 'PURO-2920183',
      },
    ],
    invoices: [
      {
        id: 'inv-008-1',
        customerId: 'c-008',
        invoiceNumber: 'INV-2025-0048',
        date: '2025-04-12',
        dueDate: '2025-05-12',
        items: 'Medical Device Trackers x15',
        subtotal: 18000,
        tax: 2340,
        total: 20340,
        amountPaid: 20340,
        status: 'Paid',
      },
      {
        id: 'inv-008-2',
        customerId: 'c-008',
        invoiceNumber: 'INV-2025-0085',
        date: '2025-05-01',
        dueDate: '2025-05-31',
        items: 'HIPAA Compliance Support Package',
        subtotal: 14000,
        tax: 1820,
        total: 15820,
        amountPaid: 0,
        status: 'Sent',
      },
    ],
    orders: [
      {
        id: 'o-008-1',
        customerId: 'c-008',
        orderNumber: 'ORD-2025-0412',
        type: 'B2B',
        date: '2025-04-12',
        itemCount: 1,
        items: 'Medical Device Trackers',
        subtotal: 18000,
        discount: 0,
        tax: 2340,
        total: 20340,
        status: 'Completed',
        channel: 'Enterprise Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-008-1',
        customerId: 'c-008',
        channel: 'Video Call',
        direction: 'Inbound',
        date: '2025-05-16T15:00:00Z',
        subject: 'HIPAA Renewal Planning',
        summary: 'Rachel reviewed compliance renewal timeline. BAA must be updated and signed before July 1. Agreed that legal would send draft by June 10.',
        loggedBy: 'Sarah Kim',
        loggedByInitials: 'SK',
        duration: '35 min',
      },
    ],
    followUps: [
      {
        id: 'fu-008-1',
        customerId: 'c-008',
        title: 'Send Updated BAA for Signature',
        description: 'Legal to prepare and send Business Associate Agreement to Rachel for HIPAA renewal.',
        dueDate: '2025-06-10',
        priority: 'High',
        status: 'Pending',
        assignedTo: 'Sarah Kim',
        assignedToInitials: 'SK',
      },
    ],
  },
  {
    id: 'c-009',
    name: 'Diego Santos',
    email: 'diego.santos@optilux.br',
    phone: '+55 11 3040 2200',
    company: 'OptiLux Brasil',
    type: 'B2B',
    status: 'Inactive',
    tags: ['Retail', 'Churn Risk', 'LATAM'],
    loyaltyPoints: 1200,
    address: 'Av. Paulista 2337',
    city: 'São Paulo',
    country: 'Brazil',
    industry: 'Retail',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2022-05-10',
    lastActivity: '2025-02-28',
    totalRevenue: 62000,
    totalOrders: 7,
    openInvoices: 0,
    healthScore: 38,
    notes: [
      {
        id: 'n-009-1',
        customerId: 'c-009',
        content: 'No contact since February. Last interaction was a support ticket. High churn risk — consider a win-back campaign or special offer.',
        author: 'Alex Torres',
        authorInitials: 'AT',
        createdAt: '2025-04-15T10:00:00Z',
        pinned: true,
      },
    ],
    deliveries: [
      {
        id: 'd-009-1',
        customerId: 'c-009',
        orderRef: 'ORD-2024-1201',
        items: 'Display Units x6',
        address: 'Av. Paulista 2337, São Paulo',
        status: 'Delivered',
        driver: 'Correios Expresso',
        scheduledDate: '2024-12-10',
        deliveredDate: '2024-12-12',
        trackingNumber: 'COR-BR-1029384',
      },
    ],
    invoices: [
      {
        id: 'inv-009-1',
        customerId: 'c-009',
        invoiceNumber: 'INV-2024-0420',
        date: '2024-12-01',
        dueDate: '2024-12-31',
        items: 'Display Units x6',
        subtotal: 12000,
        tax: 2160,
        total: 14160,
        amountPaid: 14160,
        status: 'Paid',
      },
    ],
    orders: [
      {
        id: 'o-009-1',
        customerId: 'c-009',
        orderNumber: 'ORD-2024-1201',
        type: 'Online',
        date: '2024-12-01',
        itemCount: 1,
        items: 'Display Units x6',
        subtotal: 12000,
        discount: 600,
        tax: 2160,
        total: 13560,
        status: 'Completed',
        channel: 'Web Store',
      },
    ],
    conversations: [
      {
        id: 'conv-009-1',
        customerId: 'c-009',
        channel: 'Email',
        direction: 'Outbound',
        date: '2025-04-15T11:00:00Z',
        subject: 'Check-in — Win-Back Outreach',
        summary: 'Sent re-engagement email to Diego. No response received as of follow-up date.',
        loggedBy: 'Alex Torres',
        loggedByInitials: 'AT',
      },
    ],
    followUps: [
      {
        id: 'fu-009-1',
        customerId: 'c-009',
        title: 'Win-Back Call — OptiLux Brasil',
        description: 'Call Diego directly. Offer 10% discount on next order or a free trial of the new analytics module.',
        dueDate: '2025-05-30',
        priority: 'Medium',
        status: 'Pending',
        assignedTo: 'Alex Torres',
        assignedToInitials: 'AT',
      },
    ],
  },
  {
    id: 'c-010',
    name: 'Fatima Al-Rashidi',
    email: 'fatima.alrashidi@qatarfin.qa',
    phone: '+974 4404 2200',
    company: 'Qatar Financial Holdings',
    type: 'Enterprise',
    status: 'VIP',
    tags: ['Finance', 'Middle East', 'Tier-1'],
    loyaltyPoints: 24500,
    address: 'West Bay, Diplomatic District',
    city: 'Doha',
    country: 'Qatar',
    industry: 'Financial Services',
    accountManager: 'Marcus Reid',
    accountManagerInitials: 'MR',
    createdAt: '2020-03-01',
    lastActivity: '2025-05-22',
    totalRevenue: 1850000,
    totalOrders: 94,
    openInvoices: 2,
    healthScore: 95,
    notes: [
      {
        id: 'n-010-1',
        customerId: 'c-010',
        content: 'Fatima confirmed they will expand to three new regional offices in 2025 — Riyadh, Cairo, and Abu Dhabi. Each will need full platform licensing.',
        author: 'Marcus Reid',
        authorInitials: 'MR',
        createdAt: '2025-05-22T14:00:00Z',
        pinned: true,
      },
    ],
    deliveries: [
      {
        id: 'd-010-1',
        customerId: 'c-010',
        orderRef: 'ORD-2025-0520',
        items: 'Secure Workstations x10, Smart Cards x100',
        address: 'West Bay, Diplomatic District, Doha',
        status: 'In Transit',
        driver: 'Aramex Priority',
        scheduledDate: '2025-05-30',
        trackingNumber: 'ARAMEX-QA-1029384',
      },
    ],
    invoices: [
      {
        id: 'inv-010-1',
        customerId: 'c-010',
        invoiceNumber: 'INV-2025-0080',
        date: '2025-05-01',
        dueDate: '2025-05-31',
        items: 'Annual Multi-Region Platform License',
        subtotal: 480000,
        tax: 0,
        total: 480000,
        amountPaid: 480000,
        status: 'Paid',
      },
      {
        id: 'inv-010-2',
        customerId: 'c-010',
        invoiceNumber: 'INV-2025-0110',
        date: '2025-05-20',
        dueDate: '2025-06-19',
        items: 'Secure Workstations x10 + Smart Cards x100',
        subtotal: 68000,
        tax: 0,
        total: 68000,
        amountPaid: 0,
        status: 'Sent',
      },
    ],
    orders: [
      {
        id: 'o-010-1',
        customerId: 'c-010',
        orderNumber: 'ORD-2025-0520',
        type: 'B2B',
        date: '2025-05-20',
        itemCount: 2,
        items: 'Workstations, Smart Cards',
        subtotal: 68000,
        discount: 3400,
        tax: 0,
        total: 64600,
        status: 'Processing',
        channel: 'Enterprise Portal',
      },
    ],
    conversations: [
      {
        id: 'conv-010-1',
        customerId: 'c-010',
        channel: 'In-Person',
        direction: 'Inbound',
        date: '2025-05-22T09:00:00Z',
        subject: 'Regional Expansion Planning',
        summary: 'Fatima met with Marcus in Doha. Confirmed three new offices opening in Riyadh, Cairo, and Abu Dhabi by end of Q3. Full platform license will be required for each.',
        loggedBy: 'Marcus Reid',
        loggedByInitials: 'MR',
        duration: '2 hrs',
      },
    ],
    followUps: [
      {
        id: 'fu-010-1',
        customerId: 'c-010',
        title: 'Multi-Region License Proposal',
        description: 'Prepare and send a consolidated regional licensing proposal for Riyadh, Cairo, and Abu Dhabi offices.',
        dueDate: '2025-06-05',
        priority: 'High',
        status: 'Pending',
        assignedTo: 'Marcus Reid',
        assignedToInitials: 'MR',
      },
    ],
  },
  // Additional customers (11–25) — compact for brevity
  {
    id: 'c-011',
    name: 'Nguyen Thi Lan',
    email: 'lan.nguyen@phoenixvn.com',
    phone: '+84 28 3822 9900',
    company: 'Phoenix Vietnam',
    type: 'B2B',
    status: 'Active',
    tags: ['Manufacturing', 'APAC'],
    loyaltyPoints: 5400,
    address: '100 Nguyen Hue Blvd',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    industry: 'Manufacturing',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2023-01-10',
    lastActivity: '2025-05-05',
    totalRevenue: 98000,
    totalOrders: 11,
    openInvoices: 1,
    healthScore: 72,
    notes: [{ id: 'n-011-1', customerId: 'c-011', content: 'Lan requested faster shipping for urgent production batches. Explore air freight option.', author: 'Alex Torres', authorInitials: 'AT', createdAt: '2025-05-05T08:00:00Z' }],
    deliveries: [{ id: 'd-011-1', customerId: 'c-011', orderRef: 'ORD-2025-0430', items: 'Production Parts x200', address: '100 Nguyen Hue Blvd, HCMC', status: 'In Transit', driver: 'DHL Air', scheduledDate: '2025-05-28', trackingNumber: 'DHL-AIR-9938211' }],
    invoices: [{ id: 'inv-011-1', customerId: 'c-011', invoiceNumber: 'INV-2025-0074', date: '2025-04-30', dueDate: '2025-05-30', items: 'Production Parts x200', subtotal: 22000, tax: 2200, total: 24200, amountPaid: 0, status: 'Sent' }],
    orders: [{ id: 'o-011-1', customerId: 'c-011', orderNumber: 'ORD-2025-0430', type: 'B2B', date: '2025-04-30', itemCount: 1, items: 'Production Parts x200', subtotal: 22000, discount: 0, tax: 2200, total: 24200, status: 'Processing', channel: 'Sales Portal' }],
    conversations: [{ id: 'conv-011-1', customerId: 'c-011', channel: 'Email', direction: 'Inbound', date: '2025-05-05T08:00:00Z', subject: 'Urgent Shipping Request', summary: 'Lan asked about expedited shipping. Advised on air freight surcharges.', loggedBy: 'Alex Torres', loggedByInitials: 'AT' }],
    followUps: [{ id: 'fu-011-1', customerId: 'c-011', title: 'Air Freight Quote', description: 'Get air freight pricing from logistics team and send to Lan.', dueDate: '2025-05-27', priority: 'Medium', status: 'Pending', assignedTo: 'Alex Torres', assignedToInitials: 'AT' }],
  },
  {
    id: 'c-012',
    name: 'Isabelle Moreau',
    email: 'isabelle.moreau@luminareparis.fr',
    phone: '+33 1 42 72 84 00',
    company: 'Luminare Paris',
    type: 'B2C',
    status: 'Active',
    tags: ['Luxury', 'Europe'],
    loyaltyPoints: 8900,
    address: '12 Rue du Faubourg Saint-Honoré',
    city: 'Paris',
    country: 'France',
    industry: 'Luxury Goods',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2022-11-20',
    lastActivity: '2025-05-14',
    totalRevenue: 189000,
    totalOrders: 24,
    openInvoices: 0,
    healthScore: 82,
    notes: [{ id: 'n-012-1', customerId: 'c-012', content: 'Isabelle is interested in our white-glove delivery service for high-value items. Prefers all communications in French.', author: 'Sarah Kim', authorInitials: 'SK', createdAt: '2025-05-14T10:30:00Z' }],
    deliveries: [{ id: 'd-012-1', customerId: 'c-012', orderRef: 'ORD-2025-0508', items: 'Premium Display Cases x4', address: '12 Rue du Faubourg Saint-Honoré, Paris', status: 'Delivered', driver: 'Chronopost', scheduledDate: '2025-05-12', deliveredDate: '2025-05-12', trackingNumber: 'CHRONO-FR-293847' }],
    invoices: [{ id: 'inv-012-1', customerId: 'c-012', invoiceNumber: 'INV-2025-0082', date: '2025-05-08', dueDate: '2025-06-08', items: 'Premium Display Cases x4', subtotal: 9200, tax: 1840, total: 11040, amountPaid: 11040, status: 'Paid' }],
    orders: [{ id: 'o-012-1', customerId: 'c-012', orderNumber: 'ORD-2025-0508', type: 'Online', date: '2025-05-08', itemCount: 1, items: 'Premium Display Cases x4', subtotal: 9200, discount: 0, tax: 1840, total: 11040, status: 'Completed', channel: 'Web Store' }],
    conversations: [{ id: 'conv-012-1', customerId: 'c-012', channel: 'Email', direction: 'Inbound', date: '2025-05-14T10:30:00Z', subject: 'White-Glove Delivery Inquiry', summary: 'Isabelle asked about premium delivery options for fragile luxury goods. Sent brochure with white-glove service details.', loggedBy: 'Sarah Kim', loggedByInitials: 'SK' }],
    followUps: [{ id: 'fu-012-1', customerId: 'c-012', title: 'White-Glove Service Proposal', description: 'Prepare French-language proposal for premium white-glove delivery service.', dueDate: '2025-06-05', priority: 'Low', status: 'Pending', assignedTo: 'Sarah Kim', assignedToInitials: 'SK' }],
  },
  {
    id: 'c-013',
    name: 'Robert Kimani',
    email: 'robert.kimani@savannah.ke',
    phone: '+254 20 492 3400',
    company: 'Savannah Enterprises',
    type: 'B2B',
    status: 'Lead',
    tags: ['Agriculture', 'Africa', 'New Lead'],
    loyaltyPoints: 0,
    address: 'Upper Hill, Nairobi',
    city: 'Nairobi',
    country: 'Kenya',
    industry: 'Agriculture',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2025-04-01',
    lastActivity: '2025-05-03',
    totalRevenue: 0,
    totalOrders: 0,
    openInvoices: 0,
    healthScore: 45,
    notes: [{ id: 'n-013-1', customerId: 'c-013', content: 'Robert reached out after seeing our AgriTrack solution at the Nairobi Tech Expo. Very interested. Needs a demo and ROI calculation.', author: 'Sarah Kim', authorInitials: 'SK', createdAt: '2025-05-03T08:00:00Z', pinned: true }],
    deliveries: [],
    invoices: [],
    orders: [],
    conversations: [{ id: 'conv-013-1', customerId: 'c-013', channel: 'Phone', direction: 'Inbound', date: '2025-05-03T09:00:00Z', subject: 'Initial Inquiry — AgriTrack', summary: 'Robert called after the Nairobi Tech Expo. Interested in AgriTrack. Agreed to schedule a product demo in mid-May.', loggedBy: 'Sarah Kim', loggedByInitials: 'SK', duration: '15 min' }],
    followUps: [{ id: 'fu-013-1', customerId: 'c-013', title: 'AgriTrack Product Demo', description: 'Schedule and host a tailored demo of AgriTrack for Robert and his operations team.', dueDate: '2025-05-29', priority: 'High', status: 'Pending', assignedTo: 'Sarah Kim', assignedToInitials: 'SK' }],
  },
  {
    id: 'c-014',
    name: 'Elena Vasquez',
    email: 'elena.vasquez@meridianhealth.es',
    phone: '+34 91 548 3200',
    company: 'Meridian Health Spain',
    type: 'Enterprise',
    status: 'Active',
    tags: ['Healthcare', 'EU', 'Compliance'],
    loyaltyPoints: 10200,
    address: 'Paseo de la Castellana 110',
    city: 'Madrid',
    country: 'Spain',
    industry: 'Healthcare',
    accountManager: 'Marcus Reid',
    accountManagerInitials: 'MR',
    createdAt: '2021-06-15',
    lastActivity: '2025-05-11',
    totalRevenue: 412000,
    totalOrders: 35,
    openInvoices: 1,
    healthScore: 86,
    notes: [{ id: 'n-014-1', customerId: 'c-014', content: 'Elena confirmed GDPR audit scheduled for Q3. Our DPA must be updated before then. Flag for legal.', author: 'Marcus Reid', authorInitials: 'MR', createdAt: '2025-05-11T11:00:00Z', pinned: true }],
    deliveries: [{ id: 'd-014-1', customerId: 'c-014', orderRef: 'ORD-2025-0420', items: 'Medical IoT Sensors x50', address: 'Paseo de la Castellana 110, Madrid', status: 'Delivered', driver: 'MRW Courier', scheduledDate: '2025-04-25', deliveredDate: '2025-04-26', trackingNumber: 'MRW-ES-48291' }],
    invoices: [
      { id: 'inv-014-1', customerId: 'c-014', invoiceNumber: 'INV-2025-0058', date: '2025-04-20', dueDate: '2025-05-20', items: 'Medical IoT Sensors x50', subtotal: 35000, tax: 7350, total: 42350, amountPaid: 42350, status: 'Paid' },
      { id: 'inv-014-2', customerId: 'c-014', invoiceNumber: 'INV-2025-0093', date: '2025-05-10', dueDate: '2025-06-10', items: 'GDPR Compliance Consultation', subtotal: 8000, tax: 1680, total: 9680, amountPaid: 0, status: 'Sent' },
    ],
    orders: [{ id: 'o-014-1', customerId: 'c-014', orderNumber: 'ORD-2025-0420', type: 'B2B', date: '2025-04-20', itemCount: 1, items: 'Medical IoT Sensors', subtotal: 35000, discount: 0, tax: 7350, total: 42350, status: 'Completed', channel: 'Enterprise Portal' }],
    conversations: [{ id: 'conv-014-1', customerId: 'c-014', channel: 'Video Call', direction: 'Inbound', date: '2025-05-11T10:00:00Z', subject: 'GDPR Audit Prep', summary: 'Elena reviewed Q3 audit timeline. Needs updated DPA from legal by June 30. Confirmed all other compliance docs are current.', loggedBy: 'Marcus Reid', loggedByInitials: 'MR', duration: '40 min' }],
    followUps: [{ id: 'fu-014-1', customerId: 'c-014', title: 'Send Updated DPA', description: 'Legal to prepare updated Data Processing Agreement for Meridian Health Spain.', dueDate: '2025-06-30', priority: 'High', status: 'Pending', assignedTo: 'Marcus Reid', assignedToInitials: 'MR' }],
  },
  {
    id: 'c-015',
    name: 'Dmitri Volkov',
    email: 'dmitri.volkov@techprime.ae',
    phone: '+971 4 388 9900',
    company: 'TechPrime UAE',
    type: 'B2B',
    status: 'Active',
    tags: ['Technology', 'Middle East', 'Growth'],
    loyaltyPoints: 6800,
    address: 'Dubai Internet City, Building 7',
    city: 'Dubai',
    country: 'UAE',
    industry: 'Technology',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2022-09-01',
    lastActivity: '2025-05-13',
    totalRevenue: 228000,
    totalOrders: 20,
    openInvoices: 1,
    healthScore: 77,
    notes: [{ id: 'n-015-1', customerId: 'c-015', content: 'Dmitri mentioned they are scaling to 5 new regional offices across the Gulf in Q4. Significant expansion opportunity.', author: 'Alex Torres', authorInitials: 'AT', createdAt: '2025-05-13T09:00:00Z' }],
    deliveries: [{ id: 'd-015-1', customerId: 'c-015', orderRef: 'ORD-2025-0501', items: 'Server Rack Units x2', address: 'Dubai Internet City, Building 7', status: 'In Transit', driver: 'Aramex', scheduledDate: '2025-05-26', trackingNumber: 'ARAMEX-UAE-192038' }],
    invoices: [{ id: 'inv-015-1', customerId: 'c-015', invoiceNumber: 'INV-2025-0090', date: '2025-05-01', dueDate: '2025-05-31', items: 'Server Rack Units x2', subtotal: 24000, tax: 1200, total: 25200, amountPaid: 0, status: 'Sent' }],
    orders: [{ id: 'o-015-1', customerId: 'c-015', orderNumber: 'ORD-2025-0501', type: 'B2B', date: '2025-05-01', itemCount: 1, items: 'Server Rack Units x2', subtotal: 24000, discount: 1200, tax: 1200, total: 24000, status: 'Processing', channel: 'Sales Portal' }],
    conversations: [{ id: 'conv-015-1', customerId: 'c-015', channel: 'Phone', direction: 'Inbound', date: '2025-05-13T11:00:00Z', subject: 'Gulf Expansion Discussion', summary: 'Dmitri outlined plans for 5 new Gulf offices. Each will need full platform setup. Requested a scalable pricing model.', loggedBy: 'Alex Torres', loggedByInitials: 'AT', duration: '25 min' }],
    followUps: [{ id: 'fu-015-1', customerId: 'c-015', title: 'Gulf Expansion Pricing Proposal', description: 'Prepare scalable pricing model for 5-office Gulf rollout.', dueDate: '2025-06-07', priority: 'High', status: 'Pending', assignedTo: 'Alex Torres', assignedToInitials: 'AT' }],
  },
  {
    id: 'c-016',
    name: 'Kenji Watanabe',
    email: 'kenji.watanabe@synthexa.jp',
    phone: '+81 3 5403 2800',
    company: 'Synthexa Japan',
    type: 'Enterprise',
    status: 'VIP',
    tags: ['R&D', 'APAC', 'Tier-1'],
    loyaltyPoints: 16400,
    address: '2-1-1 Nihonbashi',
    city: 'Tokyo',
    country: 'Japan',
    industry: 'Research & Development',
    accountManager: 'Marcus Reid',
    accountManagerInitials: 'MR',
    createdAt: '2020-07-01',
    lastActivity: '2025-05-18',
    totalRevenue: 965000,
    totalOrders: 72,
    openInvoices: 1,
    healthScore: 91,
    notes: [{ id: 'n-016-1', customerId: 'c-016', content: 'Kenji confirmed they are partnering with us exclusively for their next 3-year R&D platform. Partnership agreement in progress.', author: 'Marcus Reid', authorInitials: 'MR', createdAt: '2025-05-18T10:00:00Z', pinned: true }],
    deliveries: [{ id: 'd-016-1', customerId: 'c-016', orderRef: 'ORD-2025-0510', items: 'Research Compute Nodes x4', address: '2-1-1 Nihonbashi, Tokyo', status: 'Delivered', driver: 'Yamato Transport', scheduledDate: '2025-05-15', deliveredDate: '2025-05-15', trackingNumber: 'YAM-JP-48291930' }],
    invoices: [{ id: 'inv-016-1', customerId: 'c-016', invoiceNumber: 'INV-2025-0100', date: '2025-05-10', dueDate: '2025-06-10', items: 'Research Compute Nodes x4 + Support', subtotal: 88000, tax: 8800, total: 96800, amountPaid: 0, status: 'Sent' }],
    orders: [{ id: 'o-016-1', customerId: 'c-016', orderNumber: 'ORD-2025-0510', type: 'B2B', date: '2025-05-10', itemCount: 2, items: 'Compute Nodes, Support Package', subtotal: 88000, discount: 4400, tax: 8800, total: 92400, status: 'Completed', channel: 'Enterprise Portal' }],
    conversations: [{ id: 'conv-016-1', customerId: 'c-016', channel: 'In-Person', direction: 'Inbound', date: '2025-05-18T09:00:00Z', subject: '3-Year Partnership Review', summary: 'Kenji and his board met with Marcus. Agreed to exclusive partnership for the next 3 years. Partnership agreement to be drafted and signed by July.', loggedBy: 'Marcus Reid', loggedByInitials: 'MR', duration: '4 hrs' }],
    followUps: [{ id: 'fu-016-1', customerId: 'c-016', title: 'Draft 3-Year Partnership Agreement', description: 'Legal to prepare exclusive 3-year partnership contract for Synthexa Japan.', dueDate: '2025-06-15', priority: 'High', status: 'Pending', assignedTo: 'Marcus Reid', assignedToInitials: 'MR' }],
  },
  {
    id: 'c-017',
    name: 'Chidi Eze',
    email: 'chidi.eze@apexng.com',
    phone: '+234 1 461 2200',
    company: 'Apex Nigeria',
    type: 'B2B',
    status: 'Active',
    tags: ['Telecom', 'Africa'],
    loyaltyPoints: 5200,
    address: 'Victoria Island, Lagos',
    city: 'Lagos',
    country: 'Nigeria',
    industry: 'Telecommunications',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2022-03-15',
    lastActivity: '2025-05-07',
    totalRevenue: 156000,
    totalOrders: 16,
    openInvoices: 0,
    healthScore: 73,
    notes: [{ id: 'n-017-1', customerId: 'c-017', content: 'Chidi requested integration with their proprietary billing system. Passed to engineering for feasibility assessment.', author: 'Sarah Kim', authorInitials: 'SK', createdAt: '2025-05-07T12:00:00Z' }],
    deliveries: [{ id: 'd-017-1', customerId: 'c-017', orderRef: 'ORD-2025-0415', items: 'Network Routers x10', address: 'Victoria Island, Lagos', status: 'Delivered', driver: 'DHL Nigeria', scheduledDate: '2025-04-22', deliveredDate: '2025-04-24', trackingNumber: 'DHL-NG-192830' }],
    invoices: [{ id: 'inv-017-1', customerId: 'c-017', invoiceNumber: 'INV-2025-0062', date: '2025-04-15', dueDate: '2025-05-15', items: 'Network Routers x10', subtotal: 28000, tax: 2800, total: 30800, amountPaid: 30800, status: 'Paid' }],
    orders: [{ id: 'o-017-1', customerId: 'c-017', orderNumber: 'ORD-2025-0415', type: 'B2B', date: '2025-04-15', itemCount: 1, items: 'Network Routers x10', subtotal: 28000, discount: 0, tax: 2800, total: 30800, status: 'Completed', channel: 'Sales Portal' }],
    conversations: [{ id: 'conv-017-1', customerId: 'c-017', channel: 'Email', direction: 'Inbound', date: '2025-05-07T12:00:00Z', subject: 'Billing Integration Request', summary: 'Chidi requested custom billing integration. Passed to engineering. ETA for feasibility: 2 weeks.', loggedBy: 'Sarah Kim', loggedByInitials: 'SK' }],
    followUps: [{ id: 'fu-017-1', customerId: 'c-017', title: 'Share Billing Integration Feasibility', description: 'Relay engineering\'s assessment on custom billing integration to Chidi.', dueDate: '2025-05-28', priority: 'Medium', status: 'Pending', assignedTo: 'Sarah Kim', assignedToInitials: 'SK' }],
  },
  {
    id: 'c-018',
    name: 'Maria Kowalski',
    email: 'maria.kowalski@polaris.pl',
    phone: '+48 22 520 4400',
    company: 'Polaris Ventures',
    type: 'B2C',
    status: 'Active',
    tags: ['Startup', 'Europe'],
    loyaltyPoints: 2100,
    address: 'ul. Marszałkowska 84/92',
    city: 'Warsaw',
    country: 'Poland',
    industry: 'Venture Capital',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2024-01-10',
    lastActivity: '2025-04-22',
    totalRevenue: 32000,
    totalOrders: 5,
    openInvoices: 0,
    healthScore: 60,
    notes: [{ id: 'n-018-1', customerId: 'c-018', content: 'Maria is a new customer from a startup accelerator referral. Small account but high growth potential as their portfolio grows.', author: 'Alex Torres', authorInitials: 'AT', createdAt: '2025-04-22T11:00:00Z' }],
    deliveries: [{ id: 'd-018-1', customerId: 'c-018', orderRef: 'ORD-2025-0310', items: 'Startup Kit x1', address: 'ul. Marszałkowska 84/92, Warsaw', status: 'Delivered', driver: 'InPost', scheduledDate: '2025-03-15', deliveredDate: '2025-03-16', trackingNumber: 'INPOST-PL-19283' }],
    invoices: [{ id: 'inv-018-1', customerId: 'c-018', invoiceNumber: 'INV-2025-0040', date: '2025-03-10', dueDate: '2025-04-10', items: 'Startup Kit x1 + 3-Month Subscription', subtotal: 4800, tax: 1104, total: 5904, amountPaid: 5904, status: 'Paid' }],
    orders: [{ id: 'o-018-1', customerId: 'c-018', orderNumber: 'ORD-2025-0310', type: 'Online', date: '2025-03-10', itemCount: 2, items: 'Startup Kit, 3-Month Subscription', subtotal: 4800, discount: 240, tax: 1104, total: 5664, status: 'Completed', channel: 'Web Store' }],
    conversations: [{ id: 'conv-018-1', customerId: 'c-018', channel: 'Chat', direction: 'Inbound', date: '2025-04-22T11:00:00Z', subject: 'Onboarding Questions', summary: 'Maria had questions about setting up her account. Walked her through the onboarding steps. Now fully set up.', loggedBy: 'Alex Torres', loggedByInitials: 'AT' }],
    followUps: [{ id: 'fu-018-1', customerId: 'c-018', title: '3-Month Check-in Call', description: 'Check in with Maria on experience after 3 months. Offer upgrade if satisfied.', dueDate: '2025-06-10', priority: 'Low', status: 'Pending', assignedTo: 'Alex Torres', assignedToInitials: 'AT' }],
  },
  {
    id: 'c-019',
    name: 'Asha Patel',
    email: 'asha.patel@solaris.in',
    phone: '+91 80 4112 3300',
    company: 'Solaris Energy India',
    type: 'Enterprise',
    status: 'Active',
    tags: ['Energy', 'India', 'Growth'],
    loyaltyPoints: 11800,
    address: 'Whitefield, Outer Ring Road',
    city: 'Bengaluru',
    country: 'India',
    industry: 'Renewable Energy',
    accountManager: 'Marcus Reid',
    accountManagerInitials: 'MR',
    createdAt: '2021-02-01',
    lastActivity: '2025-05-09',
    totalRevenue: 534000,
    totalOrders: 42,
    openInvoices: 2,
    healthScore: 85,
    notes: [{ id: 'n-019-1', customerId: 'c-019', content: 'Asha confirmed 3 new solar installations starting in Q3. Each will need IoT monitoring integration.', author: 'Marcus Reid', authorInitials: 'MR', createdAt: '2025-05-09T10:00:00Z' }],
    deliveries: [{ id: 'd-019-1', customerId: 'c-019', orderRef: 'ORD-2025-0428', items: 'IoT Monitoring Kits x30', address: 'Whitefield, ORR, Bengaluru', status: 'In Transit', driver: 'Blue Dart', scheduledDate: '2025-05-26', trackingNumber: 'BD-IN-4928103' }],
    invoices: [
      { id: 'inv-019-1', customerId: 'c-019', invoiceNumber: 'INV-2025-0076', date: '2025-04-28', dueDate: '2025-05-28', items: 'IoT Monitoring Kits x30', subtotal: 42000, tax: 7560, total: 49560, amountPaid: 0, status: 'Overdue' },
      { id: 'inv-019-2', customerId: 'c-019', invoiceNumber: 'INV-2025-0104', date: '2025-05-09', dueDate: '2025-06-09', items: 'Q2 Platform License', subtotal: 24000, tax: 4320, total: 28320, amountPaid: 0, status: 'Sent' },
    ],
    orders: [{ id: 'o-019-1', customerId: 'c-019', orderNumber: 'ORD-2025-0428', type: 'B2B', date: '2025-04-28', itemCount: 1, items: 'IoT Monitoring Kits x30', subtotal: 42000, discount: 2100, tax: 7560, total: 47460, status: 'Processing', channel: 'Enterprise Portal' }],
    conversations: [{ id: 'conv-019-1', customerId: 'c-019', channel: 'Phone', direction: 'Inbound', date: '2025-05-09T09:00:00Z', subject: 'Q3 Installation Planning', summary: 'Asha outlined Q3 installation timeline. Three sites in Karnataka. IoT monitoring kits needed at each site. Discussed integration roadmap.', loggedBy: 'Marcus Reid', loggedByInitials: 'MR', duration: '30 min' }],
    followUps: [{ id: 'fu-019-1', customerId: 'c-019', title: 'IoT Integration Timeline for Q3 Sites', description: 'Prepare deployment timeline for 3 Karnataka solar sites with IoT monitoring integration.', dueDate: '2025-06-01', priority: 'High', status: 'Pending', assignedTo: 'Marcus Reid', assignedToInitials: 'MR' }],
  },
  {
    id: 'c-020',
    name: 'Lucas Petrov',
    email: 'lucas.petrov@innobridge.pl',
    phone: '+48 12 480 2200',
    company: 'InnoBridge Poland',
    type: 'B2B',
    status: 'Lead',
    tags: ['IT Services', 'Europe', 'New Lead'],
    loyaltyPoints: 0,
    address: 'ul. Floriańska 30',
    city: 'Kraków',
    country: 'Poland',
    industry: 'IT Services',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2025-05-01',
    lastActivity: '2025-05-20',
    totalRevenue: 0,
    totalOrders: 0,
    openInvoices: 0,
    healthScore: 50,
    notes: [{ id: 'n-020-1', customerId: 'c-020', content: 'Lucas was referred by Thomas Bergmann (Kraftwerk). Very warm lead. Needs a tailored demo for IT services use case.', author: 'Alex Torres', authorInitials: 'AT', createdAt: '2025-05-20T09:00:00Z', pinned: true }],
    deliveries: [],
    invoices: [],
    orders: [],
    conversations: [{ id: 'conv-020-1', customerId: 'c-020', channel: 'Email', direction: 'Inbound', date: '2025-05-20T09:00:00Z', subject: 'Referral from Thomas Bergmann', summary: 'Lucas introduced himself via email. Thomas Bergmann referred him. Interested in IT service management platform. Demo requested.', loggedBy: 'Alex Torres', loggedByInitials: 'AT' }],
    followUps: [{ id: 'fu-020-1', customerId: 'c-020', title: 'IT Services Demo — InnoBridge', description: 'Schedule and deliver a tailored product demo for Lucas and his team.', dueDate: '2025-06-04', priority: 'High', status: 'Pending', assignedTo: 'Alex Torres', assignedToInitials: 'AT' }],
  },
  {
    id: 'c-021',
    name: 'Zanele Dlamini',
    email: 'zanele.dlamini@afrofin.co.za',
    phone: '+27 11 555 2400',
    company: 'AfroFin South Africa',
    type: 'B2B',
    status: 'Active',
    tags: ['Finance', 'Africa'],
    loyaltyPoints: 4600,
    address: '1 Sandton Drive',
    city: 'Johannesburg',
    country: 'South Africa',
    industry: 'Financial Services',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2023-04-10',
    lastActivity: '2025-05-01',
    totalRevenue: 108000,
    totalOrders: 12,
    openInvoices: 0,
    healthScore: 69,
    notes: [{ id: 'n-021-1', customerId: 'c-021', content: 'Zanele flagged interest in automated compliance reporting. Will share requirements doc by June.', author: 'Sarah Kim', authorInitials: 'SK', createdAt: '2025-05-01T10:00:00Z' }],
    deliveries: [{ id: 'd-021-1', customerId: 'c-021', orderRef: 'ORD-2025-0408', items: 'Compliance Documentation x10', address: '1 Sandton Drive, Johannesburg', status: 'Delivered', driver: 'The Courier Guy', scheduledDate: '2025-04-12', deliveredDate: '2025-04-13', trackingNumber: 'TCG-ZA-19283' }],
    invoices: [{ id: 'inv-021-1', customerId: 'c-021', invoiceNumber: 'INV-2025-0054', date: '2025-04-08', dueDate: '2025-05-08', items: 'Compliance Documentation + Annual Subscription', subtotal: 16000, tax: 2400, total: 18400, amountPaid: 18400, status: 'Paid' }],
    orders: [{ id: 'o-021-1', customerId: 'c-021', orderNumber: 'ORD-2025-0408', type: 'B2B', date: '2025-04-08', itemCount: 2, items: 'Documentation, Subscription', subtotal: 16000, discount: 0, tax: 2400, total: 18400, status: 'Completed', channel: 'Sales Portal' }],
    conversations: [{ id: 'conv-021-1', customerId: 'c-021', channel: 'Email', direction: 'Inbound', date: '2025-05-01T10:00:00Z', subject: 'Automated Compliance Reporting Interest', summary: 'Zanele expressed interest in automated compliance reports. Will send requirements document in June.', loggedBy: 'Sarah Kim', loggedByInitials: 'SK' }],
    followUps: [{ id: 'fu-021-1', customerId: 'c-021', title: 'Review Compliance Requirements Doc', description: 'Once Zanele sends requirements, assess feasibility and prepare proposal.', dueDate: '2025-06-20', priority: 'Medium', status: 'Pending', assignedTo: 'Sarah Kim', assignedToInitials: 'SK' }],
  },
  {
    id: 'c-022',
    name: 'Oliver Bennett',
    email: 'oliver.bennett@pinnacleuk.co.uk',
    phone: '+44 161 200 5500',
    company: 'Pinnacle UK',
    type: 'B2B',
    status: 'Inactive',
    tags: ['Churn Risk', 'UK', 'Price Sensitive'],
    loyaltyPoints: 1800,
    address: 'Exchange Quay, Salford',
    city: 'Manchester',
    country: 'UK',
    industry: 'Retail',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2022-08-20',
    lastActivity: '2025-01-15',
    totalRevenue: 74000,
    totalOrders: 9,
    openInvoices: 1,
    healthScore: 32,
    notes: [{ id: 'n-022-1', customerId: 'c-022', content: 'Oliver paused account citing budget cuts. Has not responded to 3 re-engagement emails. Consider a retention offer.', author: 'Alex Torres', authorInitials: 'AT', createdAt: '2025-03-01T09:00:00Z', pinned: true }],
    deliveries: [{ id: 'd-022-1', customerId: 'c-022', orderRef: 'ORD-2024-1101', items: 'Retail Analytics Platform — Annual', address: 'Exchange Quay, Salford, Manchester', status: 'Delivered', driver: 'Royal Mail', scheduledDate: '2024-11-10', deliveredDate: '2024-11-11', trackingNumber: 'RM-GB-2847391' }],
    invoices: [{ id: 'inv-022-1', customerId: 'c-022', invoiceNumber: 'INV-2025-0012', date: '2025-01-01', dueDate: '2025-01-31', items: 'Renewal Invoice — Retail Analytics', subtotal: 12000, tax: 2400, total: 14400, amountPaid: 0, status: 'Overdue' }],
    orders: [{ id: 'o-022-1', customerId: 'c-022', orderNumber: 'ORD-2024-1101', type: 'Online', date: '2024-11-01', itemCount: 1, items: 'Retail Analytics Annual License', subtotal: 12000, discount: 600, tax: 2400, total: 13800, status: 'Completed', channel: 'Web Store' }],
    conversations: [{ id: 'conv-022-1', customerId: 'c-022', channel: 'Email', direction: 'Outbound', date: '2025-03-01T09:00:00Z', subject: 'Retention Outreach', summary: 'Third re-engagement email sent. No response yet. Consider calling directly or offering a free 2-month extension.', loggedBy: 'Alex Torres', loggedByInitials: 'AT' }],
    followUps: [{ id: 'fu-022-1', customerId: 'c-022', title: 'Final Retention Call — Pinnacle UK', description: 'Last-chance direct call to Oliver. Offer 2-month free extension to reactivate account.', dueDate: '2025-05-28', priority: 'High', status: 'Overdue', assignedTo: 'Alex Torres', assignedToInitials: 'AT' }],
  },
  {
    id: 'c-023',
    name: 'Aiko Tanaka',
    email: 'aiko.tanaka@futurehome.jp',
    phone: '+81 6 6282 4400',
    company: 'FutureHome Japan',
    type: 'B2C',
    status: 'Active',
    tags: ['Smart Home', 'APAC'],
    loyaltyPoints: 7200,
    address: '2-3-1 Namba, Chuo-ku',
    city: 'Osaka',
    country: 'Japan',
    industry: 'Smart Home Technology',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2022-06-01',
    lastActivity: '2025-05-02',
    totalRevenue: 142000,
    totalOrders: 18,
    openInvoices: 0,
    healthScore: 79,
    notes: [{ id: 'n-023-1', customerId: 'c-023', content: 'Aiko is a loyal B2C buyer with a large smart home setup. Regularly upgrades devices. Candidate for our loyalty VIP upgrade.', author: 'Sarah Kim', authorInitials: 'SK', createdAt: '2025-05-02T10:00:00Z' }],
    deliveries: [{ id: 'd-023-1', customerId: 'c-023', orderRef: 'ORD-2025-0425', items: 'Smart Sensors x8, Hub v3 x1', address: '2-3-1 Namba, Osaka', status: 'Delivered', driver: 'Sagawa Express', scheduledDate: '2025-04-29', deliveredDate: '2025-04-30', trackingNumber: 'SAG-JP-382910' }],
    invoices: [{ id: 'inv-023-1', customerId: 'c-023', invoiceNumber: 'INV-2025-0072', date: '2025-04-25', dueDate: '2025-05-25', items: 'Smart Sensors x8 + Hub v3', subtotal: 3200, tax: 320, total: 3520, amountPaid: 3520, status: 'Paid' }],
    orders: [{ id: 'o-023-1', customerId: 'c-023', orderNumber: 'ORD-2025-0425', type: 'Online', date: '2025-04-25', itemCount: 2, items: 'Smart Sensors, Hub v3', subtotal: 3200, discount: 160, tax: 320, total: 3360, status: 'Completed', channel: 'Web Store' }],
    conversations: [{ id: 'conv-023-1', customerId: 'c-023', channel: 'Chat', direction: 'Inbound', date: '2025-05-02T10:00:00Z', subject: 'Upgrade Inquiry', summary: 'Aiko asked about Hub v4 release date. Informed her of Q4 release. She expressed strong interest in upgrading.', loggedBy: 'Sarah Kim', loggedByInitials: 'SK' }],
    followUps: [{ id: 'fu-023-1', customerId: 'c-023', title: 'VIP Loyalty Upgrade Notification', description: 'Notify Aiko about VIP tier upgrade eligibility and Hub v4 pre-order availability.', dueDate: '2025-06-01', priority: 'Low', status: 'Pending', assignedTo: 'Sarah Kim', assignedToInitials: 'SK' }],
  },
  {
    id: 'c-024',
    name: 'Frank Adeyemi',
    email: 'frank.adeyemi@bluewave.com.au',
    phone: '+61 2 9281 4400',
    company: 'BlueWave Australia',
    type: 'B2B',
    status: 'Active',
    tags: ['Property', 'APAC', 'Growth'],
    loyaltyPoints: 6600,
    address: '1 Market St',
    city: 'Sydney',
    country: 'Australia',
    industry: 'Property Management',
    accountManager: 'Alex Torres',
    accountManagerInitials: 'AT',
    createdAt: '2022-10-01',
    lastActivity: '2025-05-15',
    totalRevenue: 192000,
    totalOrders: 21,
    openInvoices: 1,
    healthScore: 76,
    notes: [{ id: 'n-024-1', customerId: 'c-024', content: 'Frank is expanding into Queensland and needs an additional 50 user licenses. Upsell opportunity in Q3.', author: 'Alex Torres', authorInitials: 'AT', createdAt: '2025-05-15T11:00:00Z' }],
    deliveries: [{ id: 'd-024-1', customerId: 'c-024', orderRef: 'ORD-2025-0505', items: 'Property Management Software USB x1', address: '1 Market St, Sydney', status: 'Delivered', driver: 'Australia Post', scheduledDate: '2025-05-08', deliveredDate: '2025-05-09', trackingNumber: 'AP-AU-2847190' }],
    invoices: [{ id: 'inv-024-1', customerId: 'c-024', invoiceNumber: 'INV-2025-0086', date: '2025-05-05', dueDate: '2025-06-05', items: 'Annual License + 50 Additional Users', subtotal: 18000, tax: 1800, total: 19800, amountPaid: 0, status: 'Sent' }],
    orders: [{ id: 'o-024-1', customerId: 'c-024', orderNumber: 'ORD-2025-0505', type: 'B2B', date: '2025-05-05', itemCount: 2, items: 'Annual License, User Expansion', subtotal: 18000, discount: 900, tax: 1800, total: 18900, status: 'Processing', channel: 'Account Portal' }],
    conversations: [{ id: 'conv-024-1', customerId: 'c-024', channel: 'Phone', direction: 'Inbound', date: '2025-05-15T11:00:00Z', subject: 'Queensland Expansion', summary: 'Frank confirmed expansion to Queensland with 50 new staff. Needs additional licenses. Alex to prepare upsell proposal.', loggedBy: 'Alex Torres', loggedByInitials: 'AT', duration: '12 min' }],
    followUps: [{ id: 'fu-024-1', customerId: 'c-024', title: 'Queensland License Upsell Proposal', description: 'Prepare 50-user license expansion proposal with Queensland deployment details.', dueDate: '2025-06-02', priority: 'Medium', status: 'Pending', assignedTo: 'Alex Torres', assignedToInitials: 'AT' }],
  },
  {
    id: 'c-025',
    name: 'Nadia Ivanova',
    email: 'nadia.ivanova@nordcomm.ee',
    phone: '+372 600 4400',
    company: 'NordComm Estonia',
    type: 'B2B',
    status: 'Active',
    tags: ['Telecom', 'EU', 'Fast Payer'],
    loyaltyPoints: 8800,
    address: 'Narva mnt 15',
    city: 'Tallinn',
    country: 'Estonia',
    industry: 'Telecommunications',
    accountManager: 'Sarah Kim',
    accountManagerInitials: 'SK',
    createdAt: '2021-11-01',
    lastActivity: '2025-05-19',
    totalRevenue: 264000,
    totalOrders: 26,
    openInvoices: 0,
    healthScore: 87,
    notes: [{ id: 'n-025-1', customerId: 'c-025', content: 'Nadia consistently pays within 7 days of invoice. Model customer. She has referred two other Estonian companies to us.', author: 'Sarah Kim', authorInitials: 'SK', createdAt: '2025-05-19T10:00:00Z', pinned: true }],
    deliveries: [{ id: 'd-025-1', customerId: 'c-025', orderRef: 'ORD-2025-0510', items: 'Telecom Analytics Suite License', address: 'Narva mnt 15, Tallinn', status: 'Delivered', driver: 'Omniva', scheduledDate: '2025-05-13', deliveredDate: '2025-05-13', trackingNumber: 'OMN-EE-10293' }],
    invoices: [{ id: 'inv-025-1', customerId: 'c-025', invoiceNumber: 'INV-2025-0099', date: '2025-05-10', dueDate: '2025-06-10', items: 'Telecom Analytics Suite — Annual', subtotal: 22000, tax: 4840, total: 26840, amountPaid: 26840, status: 'Paid' }],
    orders: [{ id: 'o-025-1', customerId: 'c-025', orderNumber: 'ORD-2025-0510', type: 'B2B', date: '2025-05-10', itemCount: 1, items: 'Telecom Analytics Suite', subtotal: 22000, discount: 1100, tax: 4840, total: 25740, status: 'Completed', channel: 'Account Portal' }],
    conversations: [{ id: 'conv-025-1', customerId: 'c-025', channel: 'Email', direction: 'Inbound', date: '2025-05-19T10:00:00Z', subject: 'Referral Thank-you', summary: 'Nadia forwarded thank-you note for the smooth renewal experience. Mentioned she referred NordBalt and BalticTech to us.', loggedBy: 'Sarah Kim', loggedByInitials: 'SK' }],
    followUps: [{ id: 'fu-025-1', customerId: 'c-025', title: 'Follow Up with Nadia\'s Referrals', description: 'Reach out to NordBalt and BalticTech via Nadia\'s intro email.', dueDate: '2025-06-03', priority: 'Medium', status: 'Pending', assignedTo: 'Sarah Kim', assignedToInitials: 'SK' }],
  },
];

// ----------------------------------------------------------------
// HELPER FUNCTIONS
// ----------------------------------------------------------------

export function getCustomerById(id: string): Customer | undefined {
  return customers.find((c) => c.id === id);
}

export function getCustomerStats() {
  const total = customers.length;
  const active = customers.filter((c) => c.status === 'Active' || c.status === 'VIP').length;
  const vip = customers.filter((c) => c.status === 'VIP').length;
  const leads = customers.filter((c) => c.status === 'Lead').length;
  const inactive = customers.filter((c) => c.status === 'Inactive').length;
  const totalRevenue = customers.reduce((sum, c) => sum + c.totalRevenue, 0);
  const avgOrderValue = totalRevenue / customers.reduce((sum, c) => sum + c.totalOrders, 0);
  const openInvoices = customers.reduce((sum, c) => sum + c.openInvoices, 0);

  return { total, active, vip, leads, inactive, totalRevenue, avgOrderValue, openInvoices };
}

export function formatCurrency(amount: number, currency = 'USD'): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

export function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}
