# Base stage for shared configuration and dependencies
FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Pruning stage to isolate only files needed for the site app
FROM base AS pruner
RUN npm install -g turbo

# Copy workspace configuration and entire context
COPY . .
RUN rm -rf .turbo node_modules

# Run turbo prune using the package name defined in apps/site/package.json
RUN turbo prune --scope=site --docker

# Installer stage to install dependencies
FROM base AS installer
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --frozen-lockfile

# Copy source code
COPY --from=pruner /app/out/full/ .

# Execute the Sanity seeder
CMD ["pnpm", "--filter", "site", "sanity:seed"]
