export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  DEVELOPER = 'DEVELOPER',
  CLIENT = 'CLIENT',
  MEMBER = 'MEMBER',
  CUSTOMER = 'CUSTOMER',
}

export enum MemberRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  CASHIER = 'CASHIER',
  REPORTER = 'REPORTER',
  CUSTOMER = 'CUSTOMER',
  GUEST = 'GUEST',
}

export enum RecipeDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  EXPERT = 'EXPERT',
}

export enum BatchStatus {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ExpirationStatus {
  FRESH = 'FRESH',
  NEAR_EXPIRY = 'NEAR_EXPIRY',
  EXPIRED = 'EXPIRED',
  DISPOSED = 'DISPOSED',
}

export enum DisposalReason {
  EXPIRED = 'EXPIRED',
  NEAR_EXPIRY_UNSOLD = 'NEAR_EXPIRY_UNSOLD',
  DAMAGED = 'DAMAGED',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  CONTAMINATION = 'CONTAMINATION',
  RECALL = 'RECALL',
  OTHER = 'OTHER',
}

export enum UnitType {
  MASS = 'MASS',
  VOLUME = 'VOLUME',
  LENGTH = 'LENGTH',
  AREA = 'AREA',
  COUNT = 'COUNT',
  TIME = 'TIME',
  TEMPERATURE = 'TEMPERATURE',
  ENERGY = 'ENERGY',
  CUSTOM = 'CUSTOM',
}
