/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`accounting_get_balance_sheet`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AccountingGetBalanceSheetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`accounting_get_cash_flow`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AccountingGetCashFlowError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`accounting_get_profit_loss`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AccountingGetProfitLossError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`accounting_get_tax_summary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AccountingGetTaxSummaryError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`accounting_initialize`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AccountingInitializeError {
    UnknownValue(serde_json::Value),
}


pub async fn accounting_get_balance_sheet(configuration: &configuration::Configuration, as_of_date: &str, org_slug: &str) -> Result<(), Error<AccountingGetBalanceSheetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_as_of_date = as_of_date;
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/finance/accounting/reports/balance-sheet", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("asOfDate", &p_query_as_of_date.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AccountingGetBalanceSheetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn accounting_get_cash_flow(configuration: &configuration::Configuration, start_date: &str, end_date: &str, org_slug: &str) -> Result<(), Error<AccountingGetCashFlowError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/finance/accounting/reports/cash-flow", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("startDate", &p_query_start_date.to_string())]);
    req_builder = req_builder.query(&[("endDate", &p_query_end_date.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AccountingGetCashFlowError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn accounting_get_profit_loss(configuration: &configuration::Configuration, start_date: &str, end_date: &str, org_slug: &str) -> Result<(), Error<AccountingGetProfitLossError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/finance/accounting/reports/profit-loss", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("startDate", &p_query_start_date.to_string())]);
    req_builder = req_builder.query(&[("endDate", &p_query_end_date.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AccountingGetProfitLossError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn accounting_get_tax_summary(configuration: &configuration::Configuration, start_date: &str, end_date: &str, org_slug: &str) -> Result<(), Error<AccountingGetTaxSummaryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/finance/accounting/reports/tax-summary", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("startDate", &p_query_start_date.to_string())]);
    req_builder = req_builder.query(&[("endDate", &p_query_end_date.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AccountingGetTaxSummaryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Sets up the default Chart of Accounts for an organization.
pub async fn accounting_initialize(configuration: &configuration::Configuration, org_slug: &str) -> Result<(), Error<AccountingInitializeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/finance/accounting/initialize", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AccountingInitializeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

