/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`attendance_controller_check_in`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttendanceControllerCheckInError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`attendance_controller_check_out`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttendanceControllerCheckOutError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`attendance_controller_get_logs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttendanceControllerGetLogsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`attendance_controller_get_my_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttendanceControllerGetMyStatusError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`attendance_controller_get_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttendanceControllerGetStatusError {
    UnknownValue(serde_json::Value),
}


pub async fn attendance_controller_check_in(configuration: &configuration::Configuration, org_slug: &str, check_in_dto: models::CheckInDto) -> Result<(), Error<AttendanceControllerCheckInError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_body_check_in_dto = check_in_dto;

    let uri_str = format!("{}/v3/{orgSlug}/members/attendance/check-in", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_check_in_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttendanceControllerCheckInError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn attendance_controller_check_out(configuration: &configuration::Configuration, org_slug: &str, check_out_dto: models::CheckOutDto) -> Result<(), Error<AttendanceControllerCheckOutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_body_check_out_dto = check_out_dto;

    let uri_str = format!("{}/v3/{orgSlug}/members/attendance/check-out", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_check_out_dto);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttendanceControllerCheckOutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn attendance_controller_get_logs(configuration: &configuration::Configuration, org_slug: &str, page: Option<f64>, limit: Option<f64>, sort_by: Option<&str>, sort_order: Option<&str>, member_id: Option<&str>, location_id: Option<&str>, start_date: Option<&str>, end_date: Option<&str>) -> Result<(), Error<AttendanceControllerGetLogsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;
    let p_query_page = page;
    let p_query_limit = limit;
    let p_query_sort_by = sort_by;
    let p_query_sort_order = sort_order;
    let p_query_member_id = member_id;
    let p_query_location_id = location_id;
    let p_query_start_date = start_date;
    let p_query_end_date = end_date;

    let uri_str = format!("{}/v3/{orgSlug}/members/attendance/logs", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_by {
        req_builder = req_builder.query(&[("sortBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sortOrder", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_member_id {
        req_builder = req_builder.query(&[("memberId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_location_id {
        req_builder = req_builder.query(&[("locationId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_start_date {
        req_builder = req_builder.query(&[("startDate", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_date {
        req_builder = req_builder.query(&[("endDate", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttendanceControllerGetLogsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn attendance_controller_get_my_status(configuration: &configuration::Configuration, org_slug: &str) -> Result<(), Error<AttendanceControllerGetMyStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/members/attendance/me/status", configuration.base_path, orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttendanceControllerGetMyStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn attendance_controller_get_status(configuration: &configuration::Configuration, member_id: &str, org_slug: &str) -> Result<(), Error<AttendanceControllerGetStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_member_id = member_id;
    let p_path_org_slug = org_slug;

    let uri_str = format!("{}/v3/{orgSlug}/members/attendance/{memberId}/status", configuration.base_path, memberId=crate::apis::urlencode(p_path_member_id), orgSlug=crate::apis::urlencode(p_path_org_slug));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AttendanceControllerGetStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

