/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`strapi_receive_webhook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StrapiReceiveWebhookError {
    Status401(),
    Status404(),
    UnknownValue(serde_json::Value),
}


/// Public endpoint. Configure this URL in your Strapi Settings → Webhooks panel. Signature verification uses HMAC-SHA256 via the X-Strapi-Signature header when a webhookSecret is configured.
pub async fn strapi_receive_webhook(configuration: &configuration::Configuration, connection_id: &str) -> Result<(), Error<StrapiReceiveWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_connection_id = connection_id;

    let uri_str = format!("{}/v3/webhooks/strapi/{connectionId}", configuration.base_path, connectionId=crate::apis::urlencode(p_path_connection_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StrapiReceiveWebhookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

