export const ROLE_PERMISSIONS: Record<string, string[]> = {
  OWNER: ['*'],
  ADMIN: ['*'],
  MANAGER: [
    'pos:auth',
    'pos:location:read',
    'pos:product:read',
    'pos:product:update',
    'pos:sale:read',
    'pos:sale:create',
    'pos:sale:update',
    'pos:stock:manage',
    'pos:petty-cash:create',
    'pos:petty-cash:read',
    'pos:sync',
    'bakery:batch:view',
    'bakery:batch:manage',
    'bakery:recipe:view',
    'bakery:recipe:manage',
    'bakery:template:view',
    'bakery:template:manage',
    'bakery:settings:manage',
    'product:read:all',
    'product:manage:stock',
    'product:view:stock_levels',
    'sale:read:location',
    'inventory_location:read:all',
    'customer:read:all',
    'customer:create',
    'payment:manage',
  ],
  BAKER: [
    'bakery:recipe:view',
    'bakery:batch:view',
    'bakery:batch:manage',
    'bakery:template:view',
    'bakery:template:manage',
    'pos:product:read',
    'product:view:stock_levels',
  ],
  STAFF: [
    'pos:auth',
    'pos:location:read',
    'pos:product:read',
    'pos:sale:read',
    'pos:sale:create',
    'pos:sale:update',
    'pos:petty-cash:create',
    'pos:sync',
    'sale:create',
    'product:read:all',
    'product:view:stock_levels',
    'customer:read:all',
    'customer:create',
    'payment:manage',
  ],
};
