import { createPermission, PERMISSION_ACTIONS, RESOURCES } from './constants';
/**
 * Comprehensive permission definitions organized by resource
 */
export const PERMISSION_DEFINITIONS = {
    // Organization & Administration
    organization: [
        createPermission(RESOURCES.ORGANIZATION, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.ORGANIZATION, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.ORGANIZATION, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.ORGANIZATION, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.AUDIT, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.BACKUP, PERMISSION_ACTIONS.MANAGE),
    ],
    // Members & Roles
    members: [
        createPermission(RESOURCES.MEMBER, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.MEMBER, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.MEMBER, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.MEMBER, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.MEMBER, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.ROLE, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.ROLE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.ROLE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.ROLE, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.ROLE, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.DEPARTMENT, PERMISSION_ACTIONS.MANAGE),
    ],
    // Products & Catalog
    products: [
        createPermission(RESOURCES.PRODUCT, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.PRODUCT, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.PRODUCT, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.PRODUCT, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.PRODUCT, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.CATEGORY, PERMISSION_ACTIONS.MANAGE),
    ],
    // Sales & Orders
    sales: [
        createPermission(RESOURCES.SALE, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.SALE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.SALE, PERMISSION_ACTIONS.VIEW_OWN),
        createPermission(RESOURCES.SALE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.SALE, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.SALE, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.ORDER, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.ORDER, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.ORDER, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.ORDER, PERMISSION_ACTIONS.APPROVE),
        createPermission(RESOURCES.RETURN, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.RETURN, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.RETURN, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.CASH_DRAWER, PERMISSION_ACTIONS.MANAGE),
    ],
    // Customers
    customers: [
        createPermission(RESOURCES.CUSTOMER, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.CUSTOMER, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.CUSTOMER, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.CUSTOMER, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.CUSTOMER, PERMISSION_ACTIONS.MANAGE),
    ],
    // Purchases & Suppliers
    purchases: [
        createPermission(RESOURCES.PURCHASE, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.PURCHASE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.PURCHASE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.PURCHASE, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.PURCHASE, PERMISSION_ACTIONS.APPROVE),
        createPermission(RESOURCES.PURCHASE, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.SUPPLIER, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.SUPPLIER, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.SUPPLIER, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.SUPPLIER, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.SUPPLIER, PERMISSION_ACTIONS.MANAGE),
    ],
    // Inventory & Stock
    inventory: [
        createPermission(RESOURCES.INVENTORY, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.INVENTORY, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.INVENTORY, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.STOCK, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.STOCK, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.STOCK, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.LOCATION, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.LOCATION, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.LOCATION, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.STORAGE, PERMISSION_ACTIONS.MANAGE),
    ],
    // Finance & Accounting
    finance: [
        createPermission(RESOURCES.FINANCE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.FINANCE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.FINANCE, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.FINANCE, PERMISSION_ACTIONS.APPROVE),
        createPermission(RESOURCES.INVOICE, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.INVOICE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.INVOICE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.INVOICE, PERMISSION_ACTIONS.APPROVE),
        createPermission(RESOURCES.PAYMENT, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.PAYMENT, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.PAYMENT, PERMISSION_ACTIONS.APPROVE),
        createPermission(RESOURCES.TAX, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.TAX, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.FISCAL_PERIOD, PERMISSION_ACTIONS.MANAGE),
    ],
    // Expenses & Budgets
    expenses: [
        createPermission(RESOURCES.EXPENSE, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.EXPENSE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.EXPENSE, PERMISSION_ACTIONS.VIEW_OWN),
        createPermission(RESOURCES.EXPENSE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.EXPENSE, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.EXPENSE, PERMISSION_ACTIONS.SUBMIT),
        createPermission(RESOURCES.EXPENSE, PERMISSION_ACTIONS.APPROVE),
        createPermission(RESOURCES.BUDGET, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.BUDGET, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.BUDGET, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.BUDGET, PERMISSION_ACTIONS.MANAGE),
    ],
    // Reports & Analytics
    reports: [
        createPermission(RESOURCES.REPORT, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.REPORT, PERMISSION_ACTIONS.GENERATE),
        createPermission(RESOURCES.REPORT, PERMISSION_ACTIONS.MANAGE),
    ],
    // HR & Attendance
    hr: [
        createPermission(RESOURCES.ATTENDANCE, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.ATTENDANCE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.ATTENDANCE, PERMISSION_ACTIONS.VIEW_OWN),
        createPermission(RESOURCES.ATTENDANCE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.ATTENDANCE, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.ATTENDANCE, PERMISSION_ACTIONS.APPROVE),
    ],
    // Logistics & Delivery
    logistics: [
        createPermission(RESOURCES.DELIVERY, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.DELIVERY, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.DELIVERY, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.DELIVERY, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.DRIVER, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.DRIVER, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.DRIVER, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.VEHICLE, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.VEHICLE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.VEHICLE, PERMISSION_ACTIONS.MANAGE),
    ],
    // Manufacturing
    manufacturing: [
        createPermission(RESOURCES.MANUFACTURING, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.MANUFACTURING, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.MANUFACTURING, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.MANUFACTURING, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.RAW_MATERIAL, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.RAW_MATERIAL, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.RAW_MATERIAL, PERMISSION_ACTIONS.MANAGE),
    ],
    // Marketing & Loyalty
    marketing: [
        createPermission(RESOURCES.LOYALTY, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.LOYALTY, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.LOYALTY, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.REFERRAL, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.REFERRAL, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.REFERRAL, PERMISSION_ACTIONS.MANAGE),
    ],
    // Communication
    communication: [
        createPermission(RESOURCES.CHANNEL, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.CHANNEL, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.CHANNEL, PERMISSION_ACTIONS.MANAGE),
    ],
    // Automation & API
    automation: [
        createPermission(RESOURCES.ASSISTANT, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.ASSISTANT, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.API_KEY, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.API_KEY, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.API_KEY, PERMISSION_ACTIONS.MANAGE),
    ],
    // Pricing Module
    pricing: [
        createPermission(RESOURCES.PRICING, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.PRICING, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.PRICING, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.PRICING, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.PRICING, PERMISSION_ACTIONS.MANAGE),
    ],
    // Bakery Module
    bakery: [
        createPermission(RESOURCES.BAKERY, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.BAKERY, PERMISSION_ACTIONS.CREATE),
        createPermission(RESOURCES.BAKERY, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.BAKERY, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.BAKERY, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.BAKERY, PERMISSION_ACTIONS.APPROVE),
    ],
    // Huly Module
    huly: [
        createPermission(RESOURCES.HULY, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.HULY, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.HULY, PERMISSION_ACTIONS.MANAGE),
    ],
    // Workspace Module
    workspace: [
        createPermission(RESOURCES.WORKSPACE, PERMISSION_ACTIONS.VIEW),
        createPermission(RESOURCES.WORKSPACE, PERMISSION_ACTIONS.EDIT),
        createPermission(RESOURCES.WORKSPACE, PERMISSION_ACTIONS.MANAGE),
        createPermission(RESOURCES.WORKSPACE, PERMISSION_ACTIONS.DELETE),
        createPermission(RESOURCES.CHANNEL, PERMISSION_ACTIONS.MANAGE),
    ],
};
