// @ts-nocheck
import { PERMISSION_ACTIONS } from './constants';
export const PERMISSION_DEFINITIONS = {
    organization: [
        PERMISSION_ACTIONS.VIEW,
        PERMISSION_ACTIONS.EDIT,
        PERMISSION_ACTIONS.MANAGE,
    ],
    members: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.MANAGE],
    products: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.CREATE, PERMISSION_ACTIONS.EDIT, PERMISSION_ACTIONS.DELETE],
    sales: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.CREATE, PERMISSION_ACTIONS.MANAGE],
    customers: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.CREATE, PERMISSION_ACTIONS.MANAGE],
    purchases: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.CREATE, PERMISSION_ACTIONS.APPROVE],
    inventory: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.MANAGE],
    finance: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.MANAGE],
    expenses: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.CREATE, PERMISSION_ACTIONS.APPROVE],
    reports: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.GENERATE],
    hr: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.MANAGE],
    communication: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.MANAGE],
    logistics: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.MANAGE],
    automation: [PERMISSION_ACTIONS.VIEW, PERMISSION_ACTIONS.MANAGE],
};
