import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { StockReportData } from '../types';

const styles = StyleSheet.create({
  page: { padding: 30 },
  section: { margin: 10, padding: 10 },
  title: { fontSize: 24, textAlign: 'center', marginBottom: 20 },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 5 },
  cell: { flex: 1, fontSize: 10 },
  header: { fontWeight: 'bold', fontSize: 12 },
});

export const StockReportDocument = ({ data }: { data: StockReportData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.title}>{data.name}</Text>
        <Text>Generated by: {data.generatedBy}</Text>
        <Text>Date: {data.date}</Text>
        <Text>Organization: {data.organization.name}</Text>
      </View>
      <View style={styles.section}>
        <View style={[styles.row, styles.header]}>
          <Text style={[styles.cell, { flex: 2 }]}>Item</Text>
          <Text style={styles.cell}>SKU</Text>
          <Text style={styles.cell}>Quantity</Text>
        </View>
        {data.items.map((item, i) => (
          <View key={i} style={styles.row}>
            <Text style={[styles.cell, { flex: 2 }]}>{item.productName} {item.variantName}</Text>
            <Text style={styles.cell}>{item.sku}</Text>
            <Text style={styles.cell}>{item.currentStock} {item.unit}</Text>
          </View>
        ))}
      </View>
    </Page>
  </Document>
);
