export declare const env: {
    NODE_ENV: "development" | "test" | "production";
    DATABASE_URL: string;
    PORT: number;
    BETTER_AUTH_SECRET: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    USE_IOREDIS_IN_PROD: boolean;
    JWT_SECRET: string;
    APP_VERSION: string;
    GITHUB_OWNER: string;
    GITHUB_REPO: string;
    STORAGE_PROVIDER: "sanity" | "rustfs";
    RUSTFS_REGION: string;
    RUSTFS_BUCKET: string;
    RUSTFS_FORCE_PATH_STYLE: boolean;
    REALTIME_PROVIDER: "ably" | "socketio";
    SOCKET_URL: string;
    GITHUB_CLIENT_ID?: string | undefined;
    GITHUB_CLIENT_SECRET?: string | undefined;
    GOOGLE_CLIENT_ID?: string | undefined;
    GOOGLE_CLIENT_SECRET?: string | undefined;
    REDIS_URL?: string | undefined;
    UPSTASH_REDIS_REST_URL?: string | undefined;
    UPSTASH_REDIS_REST_TOKEN?: string | undefined;
    INTERNAL_ADMIN_SECRET?: string | undefined;
    ZITADEL_DOMAIN?: string | undefined;
    ZITADEL_CLIENT_ID?: string | undefined;
    ZITADEL_API_URL?: string | undefined;
    ZITADEL_ORG_ID?: string | undefined;
    ZITADEL_PROJECT_ID?: string | undefined;
    SLACK_CLIENT_ID?: string | undefined;
    SLACK_CLIENT_SECRET?: string | undefined;
    SLACK_REDIRECT_URI?: string | undefined;
    GITHUB_TOKEN?: string | undefined;
    OPENOBSERVE_URL?: string | undefined;
    OPENOBSERVE_ORG?: string | undefined;
    OPENOBSERVE_STREAM?: string | undefined;
    OPENOBSERVE_TOKEN?: string | undefined;
    SANITY_PROJECT_ID?: string | undefined;
    SANITY_DATASET?: string | undefined;
    SANITY_API_TOKEN?: string | undefined;
    RUSTFS_ENDPOINT?: string | undefined;
    RUSTFS_ACCESS_KEY?: string | undefined;
    RUSTFS_SECRET_KEY?: string | undefined;
    RUSTFS_PUBLIC_URL?: string | undefined;
    ABLY_API_KEY?: string | undefined;
} & {
    NEXT_PUBLIC_APP_URL: string;
    NEXT_PUBLIC_API_URL: string;
    NEXT_PUBLIC_WEB_URL: string;
    NEXT_PUBLIC_CRM_URL: string;
    NEXT_PUBLIC_REALTIME_PROVIDER: "ably" | "socketio";
    NEXT_PUBLIC_SOCKET_URL: string;
    NEXT_PUBLIC_COOKIE_DOMAIN?: string | undefined;
};
export type Env = typeof env;
