"use client";

import React, { useState, useRef } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from "@repo/ui/components/ui/dialog";
import { Button } from "@repo/ui/components/ui/button";
import { Input } from "@repo/ui/components/ui/input";
import { Label } from "@repo/ui/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@repo/ui/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@repo/ui/components/ui/table";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@repo/ui/components/ui/popover";
import {
  Upload,
  FileSpreadsheet,
  ArrowRight,
  CheckCircle2,
  AlertCircle,
  HelpCircle,
  Loader2,
  ChevronLeft,
  ChevronRight,
  X,
  Download,
} from "lucide-react";
import Papa from "papaparse";
import * as XLSX from "xlsx";
import { toast } from "sonner";
import {
  importProducts,
  type ProductImportData,
} from "../../app/actions/inventory";

type Step = "UPLOAD" | "MAPPING" | "GROUPING" | "PREVIEW" | "RESULTS";

interface ProductGroup {
  id: string;
  name: string;
  categoryName: string;
  description?: string;
  variants: {
    id: string;
    variantName: string;
    originalRowIndex: number;
  }[];
}

const REQUIRED_FIELDS = [
  { key: "name", label: "Product Name" },
  { key: "buyingPrice", label: "Buying Price" },
  { key: "retailPrice", label: "Retail Price" },
];

const OPTIONAL_FIELDS = [
  { key: "sku", label: "SKU (Autogenerated if empty)" },
  { key: "categoryName", label: "Category (Defaults to Uncategorized)" },
  { key: "initialStock", label: "Initial Stock" },
  { key: "description", label: "Description" },
  { key: "barcode", label: "Barcode" },
];

const ALL_FIELDS = [...REQUIRED_FIELDS, ...OPTIONAL_FIELDS];

export function ProductImport({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState<Step>("UPLOAD");
  const [file, setFile] = useState<File | null>(null);
  const [csvData, setCsvData] = useState<any[]>([]);
  const [headers, setHeaders] = useState<string[]>([]);
  const [mappings, setMappings] = useState<Record<string, string>>({});
  const [groups, setGroups] = useState<ProductGroup[]>([]);
  const [strategy, setStrategy] = useState<"skip" | "replace">("skip");
  const [isImporting, setIsImporting] = useState(false);
  const [results, setResults] = useState<{
    success: number;
    skipped: number;
    replaced: number;
    failed: number;
    errors: string[];
  } | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const reset = () => {
    setStep("UPLOAD");
    setFile(null);
    setCsvData([]);
    setHeaders([]);
    setMappings({});
    setGroups([]);
    setStrategy("skip");
    setIsImporting(false);
    setResults(null);
  };

  const onFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (!selectedFile) return;

    if (selectedFile.size > 10 * 1024 * 1024) {
      toast.error("File size exceeds 10MB limit");
      return;
    }

    const isCsv = selectedFile.name.endsWith(".csv");
    const isExcel =
      selectedFile.name.endsWith(".xlsx") || selectedFile.name.endsWith(".xls");

    if (!isCsv && !isExcel) {
      toast.error("Please upload a CSV or Excel file");
      return;
    }

    setFile(selectedFile);

    if (isCsv) {
      Papa.parse(selectedFile, {
        header: true,
        skipEmptyLines: true,
        complete: results => {
          handleDataParsed(results.data);
        },
        error: error => {
          toast.error(`Error parsing CSV: ${error.message}`);
        },
      });
    } else {
      try {
        const data = await parseExcel(selectedFile);
        handleDataParsed(data);
      } catch (error: any) {
        toast.error(`Error parsing Excel: ${error.message}`);
      }
    }
  };

  const parseExcel = (file: File): Promise<any[]> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = e => {
        try {
          const bstr = e.target?.result;
          const wb = XLSX.read(bstr, { type: "binary" });
          const wsname = wb.SheetNames[0];
          const ws = wb.Sheets[wsname];
          const data = XLSX.utils.sheet_to_json(ws);
          resolve(data);
        } catch (err) {
          reject(err);
        }
      };
      reader.onerror = err => reject(err);
      reader.readAsBinaryString(file);
    });
  };

  const handleDataParsed = (data: any[]) => {
    if (data.length === 0) {
      toast.error("The file is empty");
      return;
    }
    setCsvData(data);
    setHeaders(Object.keys(data[0]));

    // Auto-mapping attempt
    const initialMappings: Record<string, string> = {};
    const csvHeaders = Object.keys(data[0]);

    ALL_FIELDS.forEach(field => {
      const match = csvHeaders.find(
        h =>
          h.toLowerCase() === field.label.toLowerCase() ||
          h.toLowerCase() === field.key.toLowerCase(),
      );
      if (match) initialMappings[field.key] = match;
    });

    setMappings(initialMappings);
    setStep("MAPPING");
  };

  const findLongestCommonPrefix = (strings: string[]) => {
    if (strings.length === 0) return "";
    let prefix = strings[0];
    for (let i = 1; i < strings.length; i++) {
      while (strings[i].indexOf(prefix) !== 0) {
        prefix = prefix.substring(0, prefix.length - 1);
        if (prefix === "") return "";
      }
    }
    // Trim to last full word
    const lastSpace = prefix.lastIndexOf(" ");
    return lastSpace > 0 ? prefix.substring(0, lastSpace).trim() : prefix;
  };

  const generateGroups = () => {
    const nameHeader = mappings.name;
    const categoryHeader = mappings.categoryName;
    const descriptionHeader = mappings.description;

    if (!nameHeader) return;

    const suggestions: ProductGroup[] = [];
    const processedIndices = new Set<number>();

    // Sort by name to find potential groups more easily
    const sortedData = csvData
      .map((row, index) => ({ row, index }))
      .sort((a, b) =>
        String(a.row[nameHeader]).localeCompare(String(b.row[nameHeader])),
      );

    for (let i = 0; i < sortedData.length; i++) {
      if (processedIndices.has(sortedData[i].index)) continue;

      const current = sortedData[i];
      const currentName = String(current.row[nameHeader]);
      const potentialGroupIndices = [i];

      for (let j = i + 1; j < sortedData.length; j++) {
        if (processedIndices.has(sortedData[j].index)) continue;

        const next = sortedData[j];
        const nextName = String(next.row[nameHeader]);

        // Heuristic: share at least the first word and have high similarity
        const firstWordCurrent = currentName.split(" ")[0];
        const firstWordNext = nextName.split(" ")[0];

        const commonPrefixLen = findLongestCommonPrefix([
          currentName,
          nextName,
        ]).length;

        if (
          (firstWordCurrent &&
            firstWordCurrent === firstWordNext &&
            commonPrefixLen >= 3) ||
          commonPrefixLen >= 5
        ) {
          potentialGroupIndices.push(j);
        } else {
          // Since it's sorted, if the first word doesn't match, we can stop looking for this group
          break;
        }
      }

      if (potentialGroupIndices.length > 1) {
        const groupRows = potentialGroupIndices.map(idx => sortedData[idx]);
        const groupNames = groupRows.map(r => String(r.row[nameHeader]));
        let commonPrefix = findLongestCommonPrefix(groupNames);

        // If no common prefix or prefix is too short, don't group automatically but maybe we should?
        // Let's be conservative.
        if (commonPrefix.length < 3) {
          commonPrefix = currentName;
          // If we can't find a good common prefix, just treat them as individual products for now
          // or use the first one's name as base.
        }

        const variants = groupRows.map(r => {
          const fullName = String(r.row[nameHeader]);
          let variantName = fullName.substring(commonPrefix.length).trim();
          if (!variantName) variantName = "Default";

          return {
            id: Math.random().toString(36).substring(7),
            variantName,
            originalRowIndex: r.index,
          };
        });

        suggestions.push({
          id: Math.random().toString(36).substring(7),
          name: commonPrefix,
          categoryName: String(
            categoryHeader && categoryHeader !== "none"
              ? groupRows[0].row[categoryHeader]
              : "Uncategorized",
          ),
          description:
            descriptionHeader && descriptionHeader !== "none"
              ? String(groupRows[0].row[descriptionHeader] || "")
              : undefined,
          variants,
        });

        potentialGroupIndices.forEach(idx =>
          processedIndices.add(sortedData[idx].index),
        );
      } else {
        // Individual product
        suggestions.push({
          id: Math.random().toString(36).substring(7),
          name: currentName,
          categoryName: String(
            categoryHeader && categoryHeader !== "none"
              ? current.row[categoryHeader]
              : "Uncategorized",
          ),
          description:
            descriptionHeader && descriptionHeader !== "none"
              ? String(current.row[descriptionHeader] || "")
              : undefined,
          variants: [
            {
              id: Math.random().toString(36).substring(7),
              variantName: "Default",
              originalRowIndex: current.index,
            },
          ],
        });
        processedIndices.add(current.index);
      }
    }

    setGroups(suggestions);
    setStep("GROUPING");
  };

  const downloadTemplate = (format: "csv" | "xlsx") => {
    const data = [
      {
        "Product Name": "Example Product",
        SKU: "EXP-001",
        Category: "Electronics",
        "Buying Price": 100,
        "Retail Price": 150,
        "Initial Stock": 10,
        Description: "A great product",
        Barcode: "123456789",
      },
      {
        "Product Name": "Sample Item",
        SKU: "SMP-002",
        Category: "Groceries",
        "Buying Price": 5,
        "Retail Price": 8,
        "Initial Stock": 50,
        Description: "Fresh and healthy",
        Barcode: "987654321",
      },
    ];

    if (format === "csv") {
      const csv = Papa.unparse(data);
      const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.setAttribute("href", url);
      link.setAttribute("download", "product_template.csv");
      link.style.visibility = "hidden";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } else {
      const worksheet = XLSX.utils.json_to_sheet(data);
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, "Products");
      XLSX.writeFile(workbook, "product_template.xlsx");
    }
  };

  const handleImport = async () => {
    setIsImporting(true);
    try {
      const productsToImport: ProductImportData[] = groups.map(group => ({
        name: group.name,
        categoryName: group.categoryName,
        description: group.description,
        variants: group.variants.map(v => {
          const row = csvData[v.originalRowIndex];
          return {
            variantName: v.variantName,
            sku:
              mappings.sku && mappings.sku !== "none"
                ? String(row[mappings.sku] || "")
                : "",
            buyingPrice:
              parseFloat(String(row[mappings.buyingPrice] || "0")) || 0,
            retailPrice:
              parseFloat(String(row[mappings.retailPrice] || "0")) || 0,
            initialStock:
              mappings.initialStock && mappings.initialStock !== "none"
                ? parseInt(String(row[mappings.initialStock] || "0")) || 0
                : 0,
            barcode:
              mappings.barcode && mappings.barcode !== "none"
                ? String(row[mappings.barcode] || "")
                : undefined,
          };
        }),
      }));

      const res = await importProducts(productsToImport, strategy);
      setResults(res);
      setStep("RESULTS");
      toast.success("Import completed");
    } catch (error: any) {
      toast.error(error.message || "Failed to import products");
    } finally {
      setIsImporting(false);
    }
  };

  const isMappingValid = REQUIRED_FIELDS.every(field => !!mappings[field.key]);

  return (
    <Dialog
      open={open}
      onOpenChange={v => {
        setOpen(v);
        if (!v) reset();
      }}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileSpreadsheet className="w-5 h-5" />
            Import Products
          </DialogTitle>
        </DialogHeader>

        {step === "UPLOAD" && (
          <div className="space-y-6">
            <div className="flex flex-col items-center justify-center p-12 border-2 border-dashed rounded-lg bg-gray-50/50 border-gray-200">
              <Upload className="w-12 h-12 mb-4 text-gray-400" />
              <h3 className="mb-2 text-lg font-medium">
                Upload your CSV or Excel file
              </h3>
              <p className="mb-6 text-sm text-gray-500">
                Maximum file size 10MB (.csv, .xlsx, .xls)
              </p>
              <Button onClick={() => fileInputRef.current?.click()}>
                Select File
              </Button>
              <input
                type="file"
                ref={fileInputRef}
                className="hidden"
                accept=".csv,.xlsx,.xls"
                onChange={onFileUpload}
              />
            </div>

            <div className="p-6 bg-blue-50/50 border border-blue-100 rounded-lg">
              <h4 className="flex items-center gap-2 mb-4 font-semibold text-blue-900">
                <Download className="w-4 h-4" />
                Need a template?
              </h4>
              <p className="mb-6 text-sm text-blue-800">
                Download our template with sample data to ensure your file is
                formatted correctly for import.
              </p>
              <div className="flex flex-wrap gap-3">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => downloadTemplate("csv")}
                  className="bg-white border-blue-200 text-blue-700 hover:bg-blue-50">
                  Download CSV Template
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => downloadTemplate("xlsx")}
                  className="bg-white border-blue-200 text-blue-700 hover:bg-blue-50">
                  Download Excel Template
                </Button>
              </div>
            </div>
          </div>
        )}

        {step === "MAPPING" && (
          <div className="space-y-6">
            <div className="grid grid-cols-2 gap-8">
              <div className="space-y-4">
                <h4 className="font-semibold text-gray-900">Map CSV Headers</h4>
                <div className="space-y-4">
                  {REQUIRED_FIELDS.map(field => (
                    <div key={field.key} className="space-y-1.5">
                      <Label className="flex items-center gap-1">
                        {field.label}
                        <span className="text-red-500">*</span>
                      </Label>
                      <Select
                        value={mappings[field.key]}
                        onValueChange={val =>
                          setMappings(prev => ({ ...prev, [field.key]: val }))
                        }>
                        <SelectTrigger>
                          <SelectValue placeholder="Select CSV header" />
                        </SelectTrigger>
                        <SelectContent>
                          {headers.map(h => (
                            <SelectItem key={h} value={h}>
                              {h}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  ))}
                  <div className="pt-4 border-t">
                    <h5 className="mb-4 text-sm font-medium text-gray-500">
                      Optional Fields
                    </h5>
                    {OPTIONAL_FIELDS.map(field => (
                      <div key={field.key} className="space-y-1.5 mb-4">
                        <Label>{field.label}</Label>
                        <Select
                          value={mappings[field.key]}
                          onValueChange={val =>
                            setMappings(prev => ({ ...prev, [field.key]: val }))
                          }>
                          <SelectTrigger>
                            <SelectValue placeholder="Select CSV header (optional)" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="none">None</SelectItem>
                            {headers.map(h => (
                              <SelectItem key={h} value={h}>
                                {h}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              <div className="p-4 border rounded-lg bg-gray-50/50">
                <h4 className="mb-4 font-semibold text-gray-900">
                  Preview (First 3 rows)
                </h4>
                <div className="space-y-4">
                  {csvData.slice(0, 3).map((row, i) => (
                    <div
                      key={i}
                      className="p-3 bg-white border rounded shadow-sm text-xs space-y-1">
                      {Object.entries(mappings).map(
                        ([key, header]) =>
                          header &&
                          header !== "none" && (
                            <div key={key} className="flex justify-between">
                              <span className="text-gray-500">{header}:</span>
                              <span className="font-medium">{row[header]}</span>
                            </div>
                          ),
                      )}
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setStep("UPLOAD")}>
                Back
              </Button>
              <Button
                disabled={!isMappingValid}
                onClick={generateGroups}>
                Continue to Grouping
                <ChevronRight className="w-4 h-4 ml-2" />
              </Button>
            </DialogFooter>
          </div>
        )}

        {step === "GROUPING" && (
          <div className="space-y-6">
            <div className="p-4 border rounded-lg bg-blue-50/50 border-blue-100 flex gap-3">
              <HelpCircle className="w-5 h-5 text-blue-600 shrink-0" />
              <div className="text-sm text-blue-800">
                <p className="font-medium">Variant Recognition</p>
                <p>
                  We&apos;ve identified potential product variants based on
                  naming patterns. You can adjust the groupings and names below.
                </p>
              </div>
            </div>

            <div className="max-h-[400px] overflow-auto border rounded-lg">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Product Name</TableHead>
                    <TableHead>Variants</TableHead>
                    <TableHead>Category</TableHead>
                    <TableHead className="w-[120px]">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {groups.map((group, groupIdx) => (
                    <TableRow key={group.id}>
                      <TableCell>
                        <Input
                          value={group.name}
                          onChange={e => {
                            const newGroups = [...groups];
                            newGroups[groupIdx].name = e.target.value;
                            setGroups(newGroups);
                          }}
                          className="h-8 py-1"
                        />
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {group.variants.map((v, vIdx) => (
                            <div
                              key={v.id}
                              className="inline-flex items-center gap-1 px-2 py-0.5 rounded bg-blue-100 text-blue-700 text-xs border border-blue-200">
                              <input
                                value={v.variantName}
                                onChange={e => {
                                  const newGroups = [...groups];
                                  newGroups[groupIdx].variants[vIdx].variantName =
                                    e.target.value;
                                  setGroups(newGroups);
                                }}
                                className="bg-transparent border-none focus:ring-0 w-16 p-0 text-xs"
                              />
                              {group.variants.length > 1 && (
                                <button
                                  onClick={() => {
                                    const newGroups = [...groups];
                                    const [variant] = newGroups[
                                      groupIdx
                                    ].variants.splice(vIdx, 1);
                                    newGroups.push({
                                      id: Math.random()
                                        .toString(36)
                                        .substring(7),
                                      name: String(
                                        csvData[variant.originalRowIndex][
                                          mappings.name
                                        ],
                                      ),
                                      categoryName: group.categoryName,
                                      description: group.description,
                                      variants: [
                                        { ...variant, variantName: "Default" },
                                      ],
                                    });
                                    setGroups(newGroups);
                                  }}
                                  className="hover:text-blue-900">
                                  <X className="w-3 h-3" />
                                </button>
                              )}
                            </div>
                          ))}
                        </div>
                      </TableCell>
                      <TableCell className="text-sm text-gray-500">
                        {group.categoryName}
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1">
                          {group.variants.length > 1 && (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="text-xs h-7 px-2"
                              onClick={() => {
                                const newGroups = [...groups];
                                const variantsToUngroup = newGroups.splice(
                                  groupIdx,
                                  1,
                                )[0].variants;
                                variantsToUngroup.forEach(v => {
                                  newGroups.push({
                                    id: Math.random().toString(36).substring(7),
                                    name: String(
                                      csvData[v.originalRowIndex][
                                        mappings.name
                                      ],
                                    ),
                                    categoryName: group.categoryName,
                                    description: group.description,
                                    variants: [
                                      { ...v, variantName: "Default" },
                                    ],
                                  });
                                });
                                setGroups(newGroups);
                              }}>
                              Ungroup
                            </Button>
                          )}
                          <Popover>
                            <PopoverTrigger asChild>
                              <Button
                                variant="ghost"
                                size="sm"
                                className="text-xs h-7 px-2">
                                Merge...
                              </Button>
                            </PopoverTrigger>
                            <PopoverContent className="w-64 p-0">
                              <div className="p-2 border-b">
                                <h5 className="text-xs font-semibold">
                                  Merge into another product
                                </h5>
                              </div>
                              <div className="max-h-48 overflow-auto p-1">
                                {groups
                                  .filter(g => g.id !== group.id)
                                  .map(targetGroup => (
                                    <button
                                      key={targetGroup.id}
                                      className="w-full text-left px-2 py-1.5 text-xs hover:bg-gray-100 rounded truncate"
                                      onClick={() => {
                                        const newGroups = [...groups];
                                        const sourceGroup = newGroups.find(
                                          g => g.id === group.id,
                                        );
                                        const targetIdx = newGroups.findIndex(
                                          g => g.id === targetGroup.id,
                                        );
                                        if (sourceGroup && targetIdx !== -1) {
                                          newGroups[targetIdx].variants.push(
                                            ...sourceGroup.variants,
                                          );
                                          const finalGroups = newGroups.filter(
                                            g => g.id !== group.id,
                                          );
                                          setGroups(finalGroups);
                                        }
                                      }}>
                                      {targetGroup.name}
                                    </button>
                                  ))}
                              </div>
                            </PopoverContent>
                          </Popover>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>

            <DialogFooter>
              <Button variant="outline" onClick={() => setStep("MAPPING")}>
                Back
              </Button>
              <Button onClick={() => setStep("PREVIEW")}>
                Continue to Preview
                <ChevronRight className="w-4 h-4 ml-2" />
              </Button>
            </DialogFooter>
          </div>
        )}

        {step === "PREVIEW" && (
          <div className="space-y-6">
            <div className="p-4 border rounded-lg bg-blue-50/50 border-blue-100 flex gap-3">
              <AlertCircle className="w-5 h-5 text-blue-600 shrink-0" />
              <div className="text-sm text-blue-800">
                <p className="font-medium">Import Summary</p>
                <p>
                  You are about to import {groups.length} products with{" "}
                  {groups.reduce((acc, g) => acc + g.variants.length, 0)} total
                  variants. Existing products with the same SKU will be handled
                  based on your selection below.
                </p>
              </div>
            </div>

            <div className="space-y-3">
              <Label>Duplicate SKU Strategy</Label>
              <div className="grid grid-cols-2 gap-4">
                <button
                  className={`p-4 border rounded-lg text-left transition-all ${strategy === "skip" ? "border-black bg-black/5 ring-1 ring-black" : "border-gray-200 hover:border-gray-300"}`}
                  onClick={() => setStrategy("skip")}>
                  <div className="font-medium">Skip</div>
                  <div className="text-xs text-gray-500">
                    Keep existing product data and ignore duplicates in CSV.
                  </div>
                </button>
                <button
                  className={`p-4 border rounded-lg text-left transition-all ${strategy === "replace" ? "border-black bg-black/5 ring-1 ring-black" : "border-gray-200 hover:border-gray-300"}`}
                  onClick={() => setStrategy("replace")}>
                  <div className="font-medium">Replace / Update</div>
                  <div className="text-xs text-gray-500">
                    Overwrite existing product details with data from CSV.
                  </div>
                </button>
              </div>
            </div>

            <div className="max-h-[300px] overflow-auto border rounded-lg">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Product Name</TableHead>
                    <TableHead>Variants</TableHead>
                    <TableHead>Category</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {groups.slice(0, 10).map((group, i) => (
                    <TableRow key={i}>
                      <TableCell className="font-medium">{group.name}</TableCell>
                      <TableCell>
                        {group.variants.map(v => v.variantName).join(", ")}
                      </TableCell>
                      <TableCell>{group.categoryName}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
              {groups.length > 10 && (
                <div className="p-3 text-center text-xs text-gray-500 border-t">
                  And {groups.length - 10} more products...
                </div>
              )}
            </div>

            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setStep("GROUPING")}
                disabled={isImporting}>
                Back
              </Button>
              <Button onClick={handleImport} disabled={isImporting}>
                {isImporting ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Importing...
                  </>
                ) : (
                  <>
                    Start Import
                    <CheckCircle2 className="w-4 h-4 ml-2" />
                  </>
                )}
              </Button>
            </DialogFooter>
          </div>
        )}

        {step === "RESULTS" && results && (
          <div className="space-y-6 py-4">
            <div className="grid grid-cols-4 gap-4">
              <div className="p-4 bg-green-50 rounded-lg border border-green-100 text-center">
                <div className="text-2xl font-bold text-green-700">
                  {results.success}
                </div>
                <div className="text-xs text-green-600 font-medium">
                  New Products
                </div>
              </div>
              <div className="p-4 bg-blue-50 rounded-lg border border-blue-100 text-center">
                <div className="text-2xl font-bold text-blue-700">
                  {results.replaced}
                </div>
                <div className="text-xs text-blue-600 font-medium">Updated</div>
              </div>
              <div className="p-4 bg-yellow-50 rounded-lg border border-yellow-100 text-center">
                <div className="text-2xl font-bold text-yellow-700">
                  {results.skipped}
                </div>
                <div className="text-xs text-yellow-600 font-medium">
                  Skipped
                </div>
              </div>
              <div className="p-4 bg-red-50 rounded-lg border border-red-100 text-center">
                <div className="text-2xl font-bold text-red-700">
                  {results.failed}
                </div>
                <div className="text-xs text-red-600 font-medium">Failed</div>
              </div>
            </div>

            {results.errors.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-sm font-semibold text-gray-900">Errors:</h4>
                <div className="max-h-[200px] overflow-y-auto p-3 bg-gray-50 border rounded-lg text-xs space-y-1 font-mono">
                  {results.errors.map((err, i) => (
                    <div key={i} className="text-red-600 flex gap-2">
                      <span className="shrink-0">•</span>
                      <span>{err}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <DialogFooter>
              <Button onClick={() => setOpen(false)}>Close</Button>
            </DialogFooter>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
