/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddBakerDto {
    /// Member ID to add as baker
    #[serde(rename = "memberId")]
    pub member_id: String,
    /// Baker specialties
    #[serde(rename = "specialties", skip_serializing_if = "Option::is_none")]
    pub specialties: Option<Vec<String>>,
    /// Is active baker
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl AddBakerDto {
    pub fn new(member_id: String) -> AddBakerDto {
        AddBakerDto {
            member_id,
            specialties: None,
            is_active: None,
        }
    }
}
