/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignDriverPartnerDto {
    /// Driver ID
    #[serde(rename = "driverId", skip_serializing_if = "Option::is_none")]
    pub driver_id: Option<String>,
    /// Delivery Partner ID
    #[serde(rename = "partnerId", skip_serializing_if = "Option::is_none")]
    pub partner_id: Option<String>,
}

impl AssignDriverPartnerDto {
    pub fn new() -> AssignDriverPartnerDto {
        AssignDriverPartnerDto {
            driver_id: None,
            partner_id: None,
        }
    }
}
