/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BanUserDto {
    /// The reason for banning the user
    #[serde(rename = "banReason", skip_serializing_if = "Option::is_none")]
    pub ban_reason: Option<String>,
    /// The expiration date of the ban
    #[serde(rename = "banExpires", skip_serializing_if = "Option::is_none")]
    pub ban_expires: Option<String>,
}

impl BanUserDto {
    pub fn new() -> BanUserDto {
        BanUserDto {
            ban_reason: None,
            ban_expires: None,
        }
    }
}

