/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CartResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "items")]
    pub items: Vec<models::CartItemDto>,
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    #[serde(rename = "sessionId", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

impl CartResponseDto {
    pub fn new(id: String, items: Vec<models::CartItemDto>) -> CartResponseDto {
        CartResponseDto {
            id,
            items,
            customer_id: None,
            session_id: None,
        }
    }
}

