/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutDto {
    #[serde(rename = "cartId")]
    pub cart_id: String,
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "phoneNumber")]
    pub phone_number: String,
    #[serde(rename = "locationId")]
    pub location_id: String,
    #[serde(rename = "notes")]
    pub notes: String,
}

impl CheckoutDto {
    pub fn new(cart_id: String, session_id: String, phone_number: String, location_id: String, notes: String) -> CheckoutDto {
        CheckoutDto {
            cart_id,
            session_id,
            phone_number,
            location_id,
            notes,
        }
    }
}

