/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutResponseDto {
    #[serde(rename = "orderId")]
    pub order_id: String,
    #[serde(rename = "paymentId")]
    pub payment_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "merchantRequestID")]
    pub merchant_request_id: String,
    #[serde(rename = "checkoutRequestID")]
    pub checkout_request_id: String,
}

impl CheckoutResponseDto {
    pub fn new(order_id: String, payment_id: String, status: String, merchant_request_id: String, checkout_request_id: String) -> CheckoutResponseDto {
        CheckoutResponseDto {
            order_id,
            payment_id,
            status,
            merchant_request_id,
            checkout_request_id,
        }
    }
}

