/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteBatchDto {
    /// Actual quantity produced
    #[serde(rename = "actualQuantity")]
    pub actual_quantity: f64,
    /// Waste quantity
    #[serde(rename = "wasteQuantity", skip_serializing_if = "Option::is_none")]
    pub waste_quantity: Option<f64>,
    /// Waste reason
    #[serde(rename = "wasteReason", skip_serializing_if = "Option::is_none")]
    pub waste_reason: Option<String>,
    /// Quality control data (JSON)
    #[serde(rename = "qcData", skip_serializing_if = "Option::is_none")]
    pub qc_data: Option<serde_json::Value>,
    /// Notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Ingredient consumptions
    #[serde(rename = "ingredientConsumptions", skip_serializing_if = "Option::is_none")]
    pub ingredient_consumptions: Option<Vec<models::IngredientConsumptionItemDto>>,
}

impl CompleteBatchDto {
    pub fn new(actual_quantity: f64) -> CompleteBatchDto {
        CompleteBatchDto {
            actual_quantity,
            waste_quantity: None,
            waste_reason: None,
            qc_data: None,
            notes: None,
            ingredient_consumptions: None,
        }
    }
}
