/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCrmActivityDto {
    #[serde(rename = "recordId")]
    pub record_id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl CreateCrmActivityDto {
    pub fn new(record_id: String, r#type: String, description: String, metadata: serde_json::Value) -> CreateCrmActivityDto {
        CreateCrmActivityDto {
            record_id,
            r#type,
            description,
            metadata,
        }
    }
}

