/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDeliveryPartnerDto {
    /// Partner name
    #[serde(rename = "name")]
    pub name: String,
    /// Email
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// Phone number
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Commission rate percentage
    #[serde(rename = "commissionRate", skip_serializing_if = "Option::is_none")]
    pub commission_rate: Option<f64>,
    /// Fixed fee amount
    #[serde(rename = "fixedFee", skip_serializing_if = "Option::is_none")]
    pub fixed_fee: Option<f64>,
    /// Benefit type
    #[serde(rename = "benefitType", skip_serializing_if = "Option::is_none")]
    pub benefit_type: Option<String>,
    /// Reconciliation policy
    #[serde(rename = "reconciliationPolicy", skip_serializing_if = "Option::is_none")]
    pub reconciliation_policy: Option<String>,
    /// Is partner active
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl CreateDeliveryPartnerDto {
    pub fn new(name: String) -> CreateDeliveryPartnerDto {
        CreateDeliveryPartnerDto {
            name,
            email: None,
            phone: None,
            address: None,
            commission_rate: None,
            fixed_fee: None,
            benefit_type: None,
            reconciliation_policy: None,
            is_active: None,
        }
    }
}
