/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateQualityIncidentDto {
    /// Title of the quality incident
    #[serde(rename = "title")]
    pub title: String,
    /// Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Severity (low, medium, high, critical)
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    /// Batch ID
    #[serde(rename = "batchId", skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<String>,
    /// Stock Batch ID
    #[serde(rename = "stockBatchId", skip_serializing_if = "Option::is_none")]
    pub stock_batch_id: Option<String>,
    /// Supplier ID
    #[serde(rename = "supplierId", skip_serializing_if = "Option::is_none")]
    pub supplier_id: Option<String>,
}

impl CreateQualityIncidentDto {
    pub fn new(title: String) -> CreateQualityIncidentDto {
        CreateQualityIncidentDto {
            title,
            description: None,
            severity: None,
            batch_id: None,
            stock_batch_id: None,
            supplier_id: None,
        }
    }
}
