/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBatchDto {
    /// Recipe ID
    #[serde(rename = "recipeId")]
    pub recipe_id: String,
    /// Planned quantity
    #[serde(rename = "plannedQuantity")]
    pub planned_quantity: f64,
    /// System unit ID
    #[serde(rename = "systemUnitId", skip_serializing_if = "Option::is_none")]
    pub system_unit_id: Option<String>,
    /// Org unit ID
    #[serde(rename = "orgUnitId", skip_serializing_if = "Option::is_none")]
    pub org_unit_id: Option<String>,
    /// Recipe multiplier
    #[serde(rename = "recipeMultiplier", skip_serializing_if = "Option::is_none")]
    pub recipe_multiplier: Option<f64>,
    /// Lead baker ID
    #[serde(rename = "leadBakerId", skip_serializing_if = "Option::is_none")]
    pub lead_baker_id: Option<String>,
    /// Assistant baker IDs
    #[serde(rename = "assistantBakerIds", skip_serializing_if = "Option::is_none")]
    pub assistant_baker_ids: Option<Vec<String>>,
    /// Notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Output inventory location ID
    #[serde(rename = "outputLocationId", skip_serializing_if = "Option::is_none")]
    pub output_location_id: Option<String>,
    /// Tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Scheduled start date/time ISO string
    #[serde(rename = "scheduledStartAt", skip_serializing_if = "Option::is_none")]
    pub scheduled_start_at: Option<String>,
    /// Date string YYYY-MM-DD
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Time string HH:mm
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl CreateBatchDto {
    pub fn new(recipe_id: String, planned_quantity: f64) -> CreateBatchDto {
        CreateBatchDto {
            recipe_id,
            planned_quantity,
            system_unit_id: None,
            org_unit_id: None,
            recipe_multiplier: None,
            lead_baker_id: None,
            assistant_baker_ids: None,
            notes: None,
            output_location_id: None,
            tags: None,
            scheduled_start_at: None,
            date: None,
            time: None,
        }
    }
}
