/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOAuthClientDto {
    /// Name of the OAuth Application
    #[serde(rename = "name")]
    pub name: String,
    /// Allowed redirect URIs for authorization callback
    #[serde(rename = "redirectUris")]
    pub redirect_uris: Vec<String>,
    /// URL to application icon/logo
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    /// URL to application homepage
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// URL to Terms of Service
    #[serde(rename = "tos", skip_serializing_if = "Option::is_none")]
    pub tos: Option<String>,
    /// URL to Privacy Policy
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    /// Whether this client is public (PKCE only, no client_secret)
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    /// Whether to skip user consent screen
    #[serde(rename = "skipConsent", skip_serializing_if = "Option::is_none")]
    pub skip_consent: Option<bool>,
}

impl CreateOAuthClientDto {
    pub fn new(name: String, redirect_uris: Vec<String>) -> CreateOAuthClientDto {
        CreateOAuthClientDto {
            name,
            redirect_uris,
            icon: None,
            uri: None,
            tos: None,
            policy: None,
            public: None,
            skip_consent: None,
        }
    }
}

