/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchDeliveryDto {
    /// Transaction ID
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
    /// Delivery Partner ID (3PL)
    #[serde(rename = "partnerId", skip_serializing_if = "Option::is_none")]
    pub partner_id: Option<String>,
    /// Driver ID (Internal)
    #[serde(rename = "driverId", skip_serializing_if = "Option::is_none")]
    pub driver_id: Option<String>,
    /// Delivery notes / instructions
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl DispatchDeliveryDto {
    pub fn new(transaction_id: String) -> DispatchDeliveryDto {
        DispatchDeliveryDto {
            transaction_id,
            partner_id: None,
            driver_id: None,
            notes: None,
        }
    }
}
