/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchStagedBatchDto {
    /// Target Front Office / POS Location ID
    #[serde(rename = "toLocationId")]
    pub to_location_id: String,
    /// Quantity to dispatch to Front Office
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// Optional notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl DispatchStagedBatchDto {
    pub fn new(to_location_id: String, quantity: f64) -> DispatchStagedBatchDto {
        DispatchStagedBatchDto {
            to_location_id,
            quantity,
            notes: None,
        }
    }
}
