/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchAddressDto {
    #[serde(rename = "street")]
    pub street: String,
    #[serde(rename = "city")]
    pub city: String,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
}

impl DispatchAddressDto {
    pub fn new(street: String, city: String) -> DispatchAddressDto {
        DispatchAddressDto {
            street,
            city,
            state: None,
            zip: None,
            country: None,
        }
    }
}

