/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DispatchOrderDto {
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
    #[serde(rename = "driverId", skip_serializing_if = "Option::is_none")]
    pub driver_id: Option<String>,
    #[serde(rename = "deliveryPartnerId", skip_serializing_if = "Option::is_none")]
    pub delivery_partner_id: Option<String>,
    #[serde(rename = "deliveryAddress", skip_serializing_if = "Option::is_none")]
    pub delivery_address: Option<Box<models::DispatchAddressDto>>,
    #[serde(rename = "estimatedTime", skip_serializing_if = "Option::is_none")]
    pub estimated_time: Option<String>,
    #[serde(rename = "deliveryFee", skip_serializing_if = "Option::is_none")]
    pub delivery_fee: Option<f64>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "manualBatches", skip_serializing_if = "Option::is_none")]
    pub manual_batches: Option<Vec<models::ManualBatchSelectionDto>>,
}

impl DispatchOrderDto {
    pub fn new(transaction_id: String) -> DispatchOrderDto {
        DispatchOrderDto {
            transaction_id,
            driver_id: None,
            delivery_partner_id: None,
            delivery_address: None,
            estimated_time: None,
            delivery_fee: None,
            notes: None,
            manual_batches: None,
        }
    }
}

