/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngredientConsumptionItemDto {
    /// Stock batch ID
    #[serde(rename = "stockBatchId")]
    pub stock_batch_id: String,
    /// Consumed quantity
    #[serde(rename = "quantity")]
    pub quantity: f64,
}

impl IngredientConsumptionItemDto {
    pub fn new(stock_batch_id: String, quantity: f64) -> IngredientConsumptionItemDto {
        IngredientConsumptionItemDto {
            stock_batch_id,
            quantity,
        }
    }
}
