/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManageProjectMemberDto {
    #[serde(rename = "memberId")]
    pub member_id: String,
    #[serde(rename = "role")]
    pub role: Role,
}

impl ManageProjectMemberDto {
    pub fn new(member_id: String, role: Role) -> ManageProjectMemberDto {
        ManageProjectMemberDto {
            member_id,
            role,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "MEMBER")]
    Member,
    #[serde(rename = "VIEWER")]
    Viewer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}
