/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberResponseDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user")]
    pub user: Box<models::UserSummaryDto>,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "membershipStatus")]
    pub membership_status: MembershipStatus,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "isCheckedIn", skip_serializing_if = "Option::is_none")]
    pub is_checked_in: Option<bool>,
    #[serde(rename = "cardId", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "departments", skip_serializing_if = "Option::is_none")]
    pub departments: Option<Vec<models::MemberDepartmentDto>>,
    #[serde(rename = "customRoles", skip_serializing_if = "Option::is_none")]
    pub custom_roles: Option<Vec<models::MemberRoleDto>>,
    #[serde(rename = "roleGroups", skip_serializing_if = "Option::is_none")]
    pub role_groups: Option<Vec<models::MemberRoleDto>>,
}

impl MemberResponseDto {
    pub fn new(id: String, user: models::UserSummaryDto, role: Role, membership_status: MembershipStatus, is_active: bool, status: Status, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> MemberResponseDto {
        MemberResponseDto {
            id,
            user: Box::new(user),
            role,
            membership_status,
            is_active,
            status,
            is_checked_in: None,
            card_id: None,
            phone: None,
            created_at,
            updated_at,
            departments: None,
            custom_roles: None,
            role_groups: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "OWNER")]
    Owner,
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "MANAGER")]
    Manager,
    #[serde(rename = "EMPLOYEE")]
    Employee,
    #[serde(rename = "CASHIER")]
    Cashier,
    #[serde(rename = "REPORTER")]
    Reporter,
    #[serde(rename = "GUEST")]
    Guest,
}

impl Default for Role {
    fn default() -> Role {
        Self::Owner
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MembershipStatus {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "PENDING_APPROVAL")]
    PendingApproval,
    #[serde(rename = "SUSPENDED")]
    Suspended,
    #[serde(rename = "REJECTED")]
    Rejected,
}

impl Default for MembershipStatus {
    fn default() -> MembershipStatus {
        Self::Active
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ONLINE")]
    Online,
    #[serde(rename = "OFFLINE")]
    Offline,
}

impl Default for Status {
    fn default() -> Status {
        Self::Online
    }
}

