/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PosReconcileDeliveryDto {
    #[serde(rename = "fulfilmentId")]
    pub fulfilment_id: String,
    #[serde(rename = "outcome")]
    pub outcome: String,
    #[serde(rename = "receivedBy", skip_serializing_if = "Option::is_none")]
    pub received_by: Option<String>,
    #[serde(rename = "proofImage", skip_serializing_if = "Option::is_none")]
    pub proof_image: Option<String>,
    #[serde(rename = "failureReason", skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
}

impl PosReconcileDeliveryDto {
    pub fn new(fulfilment_id: String, outcome: String) -> PosReconcileDeliveryDto {
        PosReconcileDeliveryDto {
            fulfilment_id,
            outcome,
            received_by: None,
            proof_image: None,
            failure_reason: None,
        }
    }
}
