/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PosCreateCustomerDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<String>,
    #[serde(rename = "customerType", skip_serializing_if = "Option::is_none")]
    pub customer_type: Option<String>,
    #[serde(rename = "gender", skip_serializing_if = "Option::is_none")]
    pub gender: Option<String>,
    #[serde(rename = "dateOfBirth", skip_serializing_if = "Option::is_none")]
    pub date_of_birth: Option<String>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "medicalHistory", skip_serializing_if = "Option::is_none")]
    pub medical_history: Option<String>,
    #[serde(rename = "allergies", skip_serializing_if = "Option::is_none")]
    pub allergies: Option<String>,
    #[serde(rename = "chronicConditions", skip_serializing_if = "Option::is_none")]
    pub chronic_conditions: Option<String>,
    #[serde(rename = "insuranceProvider", skip_serializing_if = "Option::is_none")]
    pub insurance_provider: Option<String>,
    #[serde(rename = "policyNumber", skip_serializing_if = "Option::is_none")]
    pub policy_number: Option<String>,
    #[serde(rename = "deliveryNotes", skip_serializing_if = "Option::is_none")]
    pub delivery_notes: Option<String>,
    #[serde(rename = "memberId", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
    #[serde(rename = "isBusiness", skip_serializing_if = "Option::is_none")]
    pub is_business: Option<bool>,
    #[serde(rename = "taxId", skip_serializing_if = "Option::is_none")]
    pub tax_id: Option<String>,
    #[serde(rename = "loyaltyPoints", skip_serializing_if = "Option::is_none")]
    pub loyalty_points: Option<f64>,
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "loyaltyTierId", skip_serializing_if = "Option::is_none")]
    pub loyalty_tier_id: Option<String>,
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<String>,
    #[serde(rename = "addresses", skip_serializing_if = "Option::is_none")]
    pub addresses: Option<serde_json::Value>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<serde_json::Value>,
    #[serde(rename = "pinnedLocation", skip_serializing_if = "Option::is_none")]
    pub pinned_location: Option<serde_json::Value>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl PosCreateCustomerDto {
    pub fn new(name: String) -> PosCreateCustomerDto {
        PosCreateCustomerDto {
            name,
            phone: None,
            email: None,
            company: None,
            customer_type: None,
            gender: None,
            date_of_birth: None,
            notes: None,
            medical_history: None,
            allergies: None,
            chronic_conditions: None,
            insurance_provider: None,
            policy_number: None,
            delivery_notes: None,
            member_id: None,
            is_business: None,
            tax_id: None,
            loyalty_points: None,
            is_active: None,
            loyalty_tier_id: None,
            avatar: None,
            addresses: None,
            address: None,
            pinned_location: None,
            tags: None,
        }
    }
}
