/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProofOfDeliveryDto {
    /// Recipient Signature (Base64 string or URL)
    #[serde(rename = "signatureUrl", skip_serializing_if = "Option::is_none")]
    pub signature_url: Option<String>,
    /// Proof photo URL
    #[serde(rename = "photoUrl", skip_serializing_if = "Option::is_none")]
    pub photo_url: Option<String>,
    /// Delivery PIN/Code
    #[serde(rename = "deliveryPin", skip_serializing_if = "Option::is_none")]
    pub delivery_pin: Option<String>,
    /// Recipient Name
    #[serde(rename = "recipientName", skip_serializing_if = "Option::is_none")]
    pub recipient_name: Option<String>,
}

impl ProofOfDeliveryDto {
    pub fn new() -> ProofOfDeliveryDto {
        ProofOfDeliveryDto {
            signature_url: None,
            photo_url: None,
            delivery_pin: None,
            recipient_name: None,
        }
    }
}
