/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicBookingDto {
    /// Service ID
    #[serde(rename = "serviceId")]
    pub service_id: String,
    /// Verification ID (from OTP verification)
    #[serde(rename = "verificationId")]
    pub verification_id: String,
    /// Scheduled start time
    #[serde(rename = "scheduledStartTime")]
    pub scheduled_start_time: String,
    /// Booking notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PublicBookingDto {
    pub fn new(service_id: String, verification_id: String, scheduled_start_time: String) -> PublicBookingDto {
        PublicBookingDto {
            service_id,
            verification_id,
            scheduled_start_time,
            notes: None,
        }
    }
}

