/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceivePurchaseItemDto {
    #[serde(rename = "purchaseItemId")]
    pub purchase_item_id: String,
    #[serde(rename = "batches")]
    pub batches: Vec<models::BatchReceiptDto>,
    #[serde(rename = "rejectedQuantity", skip_serializing_if = "Option::is_none")]
    pub rejected_quantity: Option<f64>,
}

impl ReceivePurchaseItemDto {
    pub fn new(purchase_item_id: String, batches: Vec<models::BatchReceiptDto>) -> ReceivePurchaseItemDto {
        ReceivePurchaseItemDto {
            purchase_item_id,
            batches,
            rejected_quantity: None,
        }
    }
}

