/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceivePurchaseDto {
    #[serde(rename = "locationId")]
    pub location_id: String,
    #[serde(rename = "items")]
    pub items: Vec<models::ReceivePurchaseItemDto>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl ReceivePurchaseDto {
    pub fn new(location_id: String, items: Vec<models::ReceivePurchaseItemDto>) -> ReceivePurchaseDto {
        ReceivePurchaseDto {
            location_id,
            items,
            notes: None,
        }
    }
}

