/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RescheduleBookingDto {
    #[serde(rename = "scheduledStartTime")]
    pub scheduled_start_time: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "scheduledEndTime", skip_serializing_if = "Option::is_none")]
    pub scheduled_end_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "staffIds", skip_serializing_if = "Option::is_none")]
    pub staff_ids: Option<Vec<String>>,
    #[serde(rename = "resourceIds", skip_serializing_if = "Option::is_none")]
    pub resource_ids: Option<Vec<String>>,
    #[serde(rename = "revision")]
    pub revision: f64,
}

impl RescheduleBookingDto {
    pub fn new(scheduled_start_time: chrono::DateTime<chrono::FixedOffset>, revision: f64) -> RescheduleBookingDto {
        RescheduleBookingDto {
            scheduled_start_time,
            scheduled_end_time: None,
            staff_ids: None,
            resource_ids: None,
            revision,
        }
    }
}
