/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaleItemDto {
    /// Product variant ID
    #[serde(rename = "variantId")]
    pub variant_id: String,
    /// Quantity of the variant purchased
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// Client provided price (validated against DB)
    #[serde(rename = "unitPrice")]
    pub unit_price: f64,
}

impl SaleItemDto {
    pub fn new(variant_id: String, quantity: f64, unit_price: f64) -> SaleItemDto {
        SaleItemDto {
            variant_id,
            quantity,
            unit_price,
        }
    }
}

