/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockRequestItemDto {
    #[serde(rename = "variantId")]
    pub variant_id: String,
    #[serde(rename = "requestedQuantity")]
    pub requested_quantity: f64,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl StockRequestItemDto {
    pub fn new(variant_id: String, requested_quantity: f64) -> StockRequestItemDto {
        StockRequestItemDto {
            variant_id,
            requested_quantity,
            reason: None,
        }
    }
}
