/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TriggerSyncDto {
    #[serde(rename = "syncTypes")]
    pub sync_types: Vec<SyncTypes>,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Direction>,
}

impl TriggerSyncDto {
    pub fn new(sync_types: Vec<SyncTypes>) -> TriggerSyncDto {
        TriggerSyncDto {
            sync_types,
            direction: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SyncTypes {
    #[serde(rename = "PRODUCTS")]
    Products,
    #[serde(rename = "INVENTORY")]
    Inventory,
    #[serde(rename = "ORDERS")]
    Orders,
    #[serde(rename = "CUSTOMERS")]
    Customers,
    #[serde(rename = "CATEGORIES")]
    Categories,
    #[serde(rename = "PRICES")]
    Prices,
}

impl Default for SyncTypes {
    fn default() -> SyncTypes {
        Self::Products
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "INBOUND")]
    Inbound,
    #[serde(rename = "OUTBOUND")]
    Outbound,
    #[serde(rename = "BIDIRECTIONAL")]
    Bidirectional,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Inbound
    }
}

