/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRecipeDto {
    /// Recipe name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Category ID
    #[serde(rename = "categoryId", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<String>,
    /// Variant ID produced by this recipe
    #[serde(rename = "producesVariantId", skip_serializing_if = "Option::is_none")]
    pub produces_variant_id: Option<String>,
    /// Yield quantity
    #[serde(rename = "yieldQuantity", skip_serializing_if = "Option::is_none")]
    pub yield_quantity: Option<f64>,
    /// System unit ID
    #[serde(rename = "systemUnitId", skip_serializing_if = "Option::is_none")]
    pub system_unit_id: Option<String>,
    /// Org unit ID
    #[serde(rename = "orgUnitId", skip_serializing_if = "Option::is_none")]
    pub org_unit_id: Option<String>,
    /// Cost price
    #[serde(rename = "costPrice", skip_serializing_if = "Option::is_none")]
    pub cost_price: Option<f64>,
    /// Recipe description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Prep time in minutes
    #[serde(rename = "prepTime", skip_serializing_if = "Option::is_none")]
    pub prep_time: Option<f64>,
    /// Bake time in minutes
    #[serde(rename = "bakeTime", skip_serializing_if = "Option::is_none")]
    pub bake_time: Option<f64>,
    /// Total time in minutes
    #[serde(rename = "totalTime", skip_serializing_if = "Option::is_none")]
    pub total_time: Option<f64>,
    /// Recipe difficulty
    #[serde(rename = "difficulty", skip_serializing_if = "Option::is_none")]
    pub difficulty: Option<String>,
    /// Baking temperature in Celsius
    #[serde(rename = "temperatureCelsius", skip_serializing_if = "Option::is_none")]
    pub temperature_celsius: Option<f64>,
    /// Serving size
    #[serde(rename = "servingSize", skip_serializing_if = "Option::is_none")]
    pub serving_size: Option<String>,
    /// Instructions text
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    /// Notes text
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Recipe tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    /// Whether the recipe is archived
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// List of recipe ingredients
    #[serde(rename = "ingredients", skip_serializing_if = "Option::is_none")]
    pub ingredients: Option<Vec<models::CreateRecipeIngredientDto>>,
}

impl UpdateRecipeDto {
    pub fn new() -> UpdateRecipeDto {
        UpdateRecipeDto {
            name: None,
            category_id: None,
            produces_variant_id: None,
            yield_quantity: None,
            system_unit_id: None,
            org_unit_id: None,
            cost_price: None,
            description: None,
            prep_time: None,
            bake_time: None,
            total_time: None,
            difficulty: None,
            temperature_celsius: None,
            serving_size: None,
            instructions: None,
            notes: None,
            tags: None,
            is_archived: None,
            ingredients: None,
        }
    }
}
