/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateMemberDto {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
    #[serde(rename = "membershipStatus", skip_serializing_if = "Option::is_none")]
    pub membership_status: Option<MembershipStatus>,
    #[serde(rename = "pin", skip_serializing_if = "Option::is_none")]
    pub pin: Option<String>,
    #[serde(rename = "cardId", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "departmentIds", skip_serializing_if = "Option::is_none")]
    pub department_ids: Option<Vec<String>>,
    #[serde(rename = "customRoleIds", skip_serializing_if = "Option::is_none")]
    pub custom_role_ids: Option<Vec<String>>,
    #[serde(rename = "roleGroupIds", skip_serializing_if = "Option::is_none")]
    pub role_group_ids: Option<Vec<String>>,
}

impl UpdateMemberDto {
    pub fn new() -> UpdateMemberDto {
        UpdateMemberDto {
            name: None,
            role: None,
            membership_status: None,
            pin: None,
            card_id: None,
            phone: None,
            is_active: None,
            status: None,
            department_ids: None,
            custom_role_ids: None,
            role_group_ids: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "OWNER")]
    Owner,
    #[serde(rename = "ADMIN")]
    Admin,
    #[serde(rename = "MANAGER")]
    Manager,
    #[serde(rename = "EMPLOYEE")]
    Employee,
    #[serde(rename = "CASHIER")]
    Cashier,
    #[serde(rename = "REPORTER")]
    Reporter,
    #[serde(rename = "GUEST")]
    Guest,
}

impl Default for Role {
    fn default() -> Role {
        Self::Owner
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MembershipStatus {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "PENDING_APPROVAL")]
    PendingApproval,
    #[serde(rename = "SUSPENDED")]
    Suspended,
    #[serde(rename = "REJECTED")]
    Rejected,
}

impl Default for MembershipStatus {
    fn default() -> MembershipStatus {
        Self::Active
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ONLINE")]
    Online,
    #[serde(rename = "OFFLINE")]
    Offline,
}

impl Default for Status {
    fn default() -> Status {
        Self::Online
    }
}

