/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePartnerDto {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "benefitType", skip_serializing_if = "Option::is_none")]
    pub benefit_type: Option<BenefitType>,
    #[serde(rename = "commissionRate", skip_serializing_if = "Option::is_none")]
    pub commission_rate: Option<f64>,
    #[serde(rename = "fixedFee", skip_serializing_if = "Option::is_none")]
    pub fixed_fee: Option<f64>,
    #[serde(rename = "reconciliationPolicy", skip_serializing_if = "Option::is_none")]
    pub reconciliation_policy: Option<ReconciliationPolicy>,
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
}

impl UpdatePartnerDto {
    pub fn new(name: String) -> UpdatePartnerDto {
        UpdatePartnerDto {
            name,
            email: None,
            phone: None,
            address: None,
            benefit_type: None,
            commission_rate: None,
            fixed_fee: None,
            reconciliation_policy: None,
            is_active: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BenefitType {
    #[serde(rename = "COMMISSION")]
    Commission,
    #[serde(rename = "FIXED_FEE")]
    FixedFee,
    #[serde(rename = "PROFIT_MARGIN")]
    ProfitMargin,
    #[serde(rename = "NONE")]
    None,
}

impl Default for BenefitType {
    fn default() -> BenefitType {
        Self::Commission
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReconciliationPolicy {
    #[serde(rename = "RETURN_TO_STOCK")]
    ReturnToStock,
    #[serde(rename = "MARK_AS_WASTE")]
    MarkAsWaste,
    #[serde(rename = "PARTNER_CHARGED")]
    PartnerCharged,
}

impl Default for ReconciliationPolicy {
    fn default() -> ReconciliationPolicy {
        Self::ReturnToStock
    }
}

