/*
 * Scryme V3 API
 *
 * The Scryme V3 API documentation - Scalable & Enterprise Ready
 *
 * The version of the OpenAPI document: 3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProductionSettingsDto {
    /// Enable production staging
    #[serde(rename = "enableProductionStaging", skip_serializing_if = "Option::is_none")]
    pub enable_production_staging: Option<bool>,
    /// Default baker ID
    #[serde(rename = "defaultBakerId", skip_serializing_if = "Option::is_none")]
    pub default_baker_id: Option<String>,
    /// Auto create daily batches
    #[serde(rename = "autoCreateDailyBatches", skip_serializing_if = "Option::is_none")]
    pub auto_create_daily_batches: Option<bool>,
    /// Expiry warning days
    #[serde(rename = "expiryWarningDays", skip_serializing_if = "Option::is_none")]
    pub expiry_warning_days: Option<f64>,
    /// Auth mode
    #[serde(rename = "authMode", skip_serializing_if = "Option::is_none")]
    pub auth_mode: Option<String>,
    /// Batch prefix
    #[serde(rename = "batchPrefix", skip_serializing_if = "Option::is_none")]
    pub batch_prefix: Option<String>,
    /// Batch separator
    #[serde(rename = "batchSeparator", skip_serializing_if = "Option::is_none")]
    pub batch_separator: Option<String>,
    /// Batch date format
    #[serde(rename = "batchDateFormat", skip_serializing_if = "Option::is_none")]
    pub batch_date_format: Option<String>,
    /// Batch sequence length
    #[serde(rename = "batchSequence", skip_serializing_if = "Option::is_none")]
    pub batch_sequence: Option<String>,
    /// Auto approve batches
    #[serde(rename = "autoApproveBatches", skip_serializing_if = "Option::is_none")]
    pub auto_approve_batches: Option<bool>,
    /// Low stock alerts
    #[serde(rename = "lowStockAlerts", skip_serializing_if = "Option::is_none")]
    pub low_stock_alerts: Option<bool>,
    /// Timezone
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl UpdateProductionSettingsDto {
    pub fn new() -> UpdateProductionSettingsDto {
        UpdateProductionSettingsDto {
            enable_production_staging: None,
            default_baker_id: None,
            auto_create_daily_batches: None,
            expiry_warning_days: None,
            auth_mode: None,
            batch_prefix: None,
            batch_separator: None,
            batch_date_format: None,
            batch_sequence: None,
            auto_approve_batches: None,
            low_stock_alerts: None,
            timezone: None,
        }
    }
}
